// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441/' | (string & {});
};

export type SeoToolkitTreeItemApiModel = {
    id: string;
    name: string;
    parentId?: null | string;
    isDraft: boolean;
    hasChildren: boolean;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoSuggestionViewModel = {
    alias?: null | string;
    config?: null | {
        [key: string]: unknown;
    };
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoSettingsFieldViewModel = {
    alias?: null | string;
    title?: null | string;
    description?: null | string;
    groupAlias?: null | string;
    suggestions?: null | Array<SeoSuggestionViewModel>;
    value?: null | string;
    userValue?: unknown;
    editView?: null | string;
    editConfig?: null | {
        [key: string]: unknown;
    };
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoFieldViewModel = {
    alias?: null | string;
    title?: null | string;
    description?: null | string;
    useInheritedValue: boolean;
    value?: unknown;
    editor?: SeoFieldEditorViewModel;
};

export type SeoFieldEditorViewModel = {
    view?: null | string;
    config?: null | {
        [key: string]: unknown;
    };
};

export type SeoFieldGroupViewModel = {
    alias?: null | string;
    name?: null | string;
    description?: null | string;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoDomainConfigViewModel = {
    domains: Array<IDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type IDomainModel = {
    domainName: string;
    isWildcard: boolean;
    languageId?: null | number | string;
    languageIsoCode?: null | string;
    rootContentId?: null | number | string;
    sortOrder: number | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type SeoDomainCollection = {
    id?: null | string;
    name: string;
    baseUrl?: null | string;
    domainIds: Array<number | string>;
    settings: {
        [key: string]: string;
    };
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number | string;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type MetaFieldsSettingsViewModel = {
    fields?: null | Array<SeoSettingsFieldViewModel>;
    groups?: null | Array<SeoFieldGroupViewModel>;
    previewers?: null | Array<FieldPreviewerViewModel>;
    seoEnabled: boolean;
};

export type FieldPreviewerViewModel = {
    group?: null | string;
    view?: null | string;
};

export type MetaFieldsSettingsPostViewModel = {
    nodeId: string;
    culture?: null | string;
    userValues?: null | {
        [key: string]: unknown;
    };
};

export type MetaFieldsAiGenerateResponseModel = {
    suggestions: Array<MetaFieldsAiFieldSuggestion>;
};

export type MetaFieldsAiFieldSuggestion = {
    alias: string;
    value: string;
};

export type MetaFieldsAiGenerateRequestModel = {
    nodeId: string;
    culture?: null | string;
};

export type FieldItemViewModel = {
    name: null | string;
    value: null | string;
    onlyShowIfInherited: boolean;
};

export type DocumentTypeValuePostViewModel = {
    useInheritedValue: boolean;
    value?: unknown;
};

export type DocumentTypeSettingsViewModel = {
    contentModel?: DocumentTypeSettingsContentViewModel;
};

export type DocumentTypeSettingsInheritanceViewModel = {
    id?: null | string;
};

export type DocumentTypeSettingsContentViewModel = {
    fields?: null | Array<SeoFieldViewModel>;
    inheritance?: DocumentTypeSettingsInheritanceViewModel;
};

export type DocumentTypeSettingsPostViewModel = {
    nodeId: string;
    enableSeoSettings: boolean;
    fields?: null | {
        [key: string]: DocumentTypeValuePostViewModel;
    };
    inheritanceId?: null | string;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number | string;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitAiGenerateData = {
    body: MetaFieldsAiGenerateRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitAI/generate';
};

export type PostUmbracoSeoToolkitAiGenerateResponses = {
    /**
     * OK
     */
    200: MetaFieldsAiGenerateResponseModel;
};

export type PostUmbracoSeoToolkitAiGenerateResponse = PostUmbracoSeoToolkitAiGenerateResponses[keyof PostUmbracoSeoToolkitAiGenerateResponses];

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/imagePreview';
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponse = GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses[keyof GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses];

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: never;
    path?: never;
    query?: {
        nodeGuid?: string;
        culture?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body: MetaFieldsSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsViewModel;
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsAdditionalFields';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses = {
    /**
     * OK
     */
    200: Array<FieldItemViewModel>;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
    };
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: DocumentTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses];

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body: DocumentTypeSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};
