// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441' | (string & {});
};

export type CreateAuditPostModel = {
    name: string;
    selectedNodeId: string;
    checks?: Array<number> | null;
    startAudit: boolean;
    maxPagesToCrawl: number;
    delayBetweenRequests: number;
};

export type CreateScriptPostModel = {
    id: number;
    key?: string | null;
    name: string;
    definitionAlias: string;
    fields?: {
        [key: string]: string | null;
    } | null;
    domainId?: string | null;
    sortOrder?: number | null;
};

export type DeleteAuditsPostModel = {
    ids?: Array<number> | null;
};

export type DeleteRedirectsPostModel = {
    ids?: Array<string> | null;
};

export type DeleteScriptPostModel = {
    ids?: Array<string> | null;
};

export type DocumentTypeSettingsContentViewModel = {
    fields?: Array<SeoFieldViewModel> | null;
    inheritance?: DocumentTypeSettingsInheritanceViewModel | null;
};

export type DocumentTypeSettingsInheritanceViewModel = {
    id?: string | null;
};

export type DocumentTypeSettingsPostViewModel = {
    nodeId: string;
    enableSeoSettings: boolean;
    fields?: {
        [key: string]: DocumentTypeValuePostViewModel | null;
    } | null;
    inheritanceId?: string | null;
};

export type DocumentTypeSettingsViewModel = {
    contentModel?: DocumentTypeSettingsContentViewModel | null;
};

export type DocumentTypeValuePostViewModel = {
    useInheritedValue: boolean;
    value?: unknown;
};

export type DomainViewModel = {
    id: number;
    name?: string | null;
};

export type FieldItemViewModel = {
    name?: string | null;
    value?: string | null;
    onlyShowIfInherited: boolean;
};

export type FieldPreviewerViewModel = {
    group?: string | null;
    view?: string | null;
};

export enum ImportRedirectsFileExtension {
    CSV = 'Csv',
    EXCEL = 'Excel'
}

export type MetaFieldsAiFieldSuggestion = {
    alias: string;
    value: string;
};

export type MetaFieldsAiGenerateRequestModel = {
    nodeId: string;
    culture?: string | null;
};

export type MetaFieldsAiGenerateResponseModel = {
    suggestions: Array<MetaFieldsAiFieldSuggestion>;
};

export type MetaFieldsSettingsPostViewModel = {
    nodeId: string;
    culture?: string | null;
    userValues?: {
        [key: string]: unknown;
    } | null;
};

export type MetaFieldsSettingsViewModel = {
    fields?: Array<SeoSettingsFieldViewModel> | null;
    groups?: Array<SeoFieldGroupViewModel> | null;
    previewers?: Array<FieldPreviewerViewModel> | null;
};

export type PagedRedirectListModel = {
    total: number;
    items: Array<RedirectListViewModel>;
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type RedirectListViewModel = {
    key: string;
    isEnabled: boolean;
    domain?: string | null;
    oldUrl?: string | null;
    newUrl?: string | null;
    statusCode: number;
    lastUpdated?: string | null;
};

export type RedirectViewModel = {
    id: number;
    key: string;
    domain?: number | null;
    customDomain?: string | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: string | null;
    newUrl?: string | null;
    newNodeId?: string | null;
    newCultureIso?: string | null;
    redirectCode: number;
    lastUpdated?: string | null;
};

export type RobotsTxtSavePostModel = {
    skipValidation: boolean;
    content?: string | null;
    domainId?: string | null;
};

export type RobotsTxtSaveResponseModel = {
    content?: string | null;
    errors?: Array<RobotsTxtValidationViewModel> | null;
};

export type RobotsTxtValidationViewModel = {
    readonly lineNumber: number;
    readonly error?: string | null;
};

export type RunPageCheckPostModel = {
    contentId: string;
};

export type SaveRedirectPostModel = {
    id: number;
    key?: string | null;
    domain?: number | null;
    customDomain?: string | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: string | null;
    newUrl?: string | null;
    newNodeId?: string | null;
    newCultureId?: string | null;
    redirectCode: number;
};

export type SchemaEntryPostModel = {
    id?: string | null;
    ownerType?: string | null;
    ownerKey: string;
    schemaAlias?: string | null;
    displayName?: string | null;
    renderAutomatically?: boolean;
    properties?: {
        [key: string]: SchemaPropertyValue | null;
    } | null;
};

export type SchemaEntryViewModel = {
    id: string;
    ownerType?: string | null;
    ownerKey: string;
    schemaAlias?: string | null;
    displayName?: string | null;
    renderAutomatically?: boolean;
    properties?: {
        [key: string]: SchemaPropertyValue | null;
    } | null;
};

export type SchemaPropertyValue = {
    value?: unknown;
    isReference: boolean;
    referenceKey?: string | null;
};

export type SchemaPropertyViewModel = {
    alias?: string | null;
    displayName?: string | null;
    propertyEditor?: string | null;
    allowReference: boolean;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type SchemaTypeViewModel = {
    alias?: string | null;
    name?: string | null;
    properties?: Array<SchemaPropertyViewModel> | null;
};

export type ScriptDefinitionViewModel = {
    readonly name?: string | null;
    readonly alias?: string | null;
    readonly fields?: Array<ScriptField> | null;
};

export type ScriptDetailViewModel = {
    id: number;
    key?: string | null;
    name?: string | null;
    definitionAlias?: string | null;
    config?: {
        [key: string]: string | null;
    } | null;
    domainId?: string | null;
    sortOrder: number;
};

export type ScriptField = {
    key?: string | null;
    name?: string | null;
    description?: string | null;
    propertyAlias?: string | null;
};

export type ScriptListViewModel = {
    id: string;
    name?: string | null;
    definitionName?: string | null;
    sortOrder: number;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoDomainCollection = {
    id?: string | null;
    name: string;
    domainIds: Array<number>;
    settings: {
        [key: string]: string;
    };
};

export type SeoDomainConfigViewModel = {
    domains: Array<UmbracoDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoFieldEditorViewModel = {
    view?: string | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type SeoFieldGroupViewModel = {
    alias?: string | null;
    name?: string | null;
    description?: string | null;
};

export type SeoFieldViewModel = {
    alias?: string | null;
    title?: string | null;
    description?: string | null;
    useInheritedValue: boolean;
    value?: unknown;
    editor?: SeoFieldEditorViewModel | null;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoSettingsFieldViewModel = {
    alias?: string | null;
    title?: string | null;
    description?: string | null;
    groupAlias?: string | null;
    suggestions?: Array<SeoSuggestionViewModel> | null;
    value?: string | null;
    allowFallback?: boolean;
    userValue?: unknown;
    editView?: string | null;
    editConfig?: {
        [key: string]: unknown;
    } | null;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoSuggestionViewModel = {
    alias?: string | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitTreeItemApiModel = {
    hasChildren: boolean;
    id: string;
    name: string;
    parentId?: string | null;
    isDraft: boolean;
};

export type SiteAuditCheckViewModel = {
    id: number;
    name?: string | null;
    description?: string | null;
    errorMessage?: string | null;
};

export type SiteAuditCreateConfigViewModel = {
    checks?: Array<SiteAuditCheckViewModel> | null;
    minimumDelayBetweenRequest: number;
    allowMinimumDelayBetweenRequestSetting: boolean;
};

export type SiteAuditDetailViewModel = {
    id: number;
    name?: string | null;
    maxPagesToCrawl?: number | null;
    totalPagesFound: number;
    progress: number;
    status?: string | null;
    checks?: Array<SiteAuditCheckViewModel> | null;
    pagesCrawled?: Array<SiteAuditPageDetailViewModel> | null;
};

export type SiteAuditOverviewViewModel = {
    id: number;
    name?: string | null;
    createdDate?: string | null;
    status?: string | null;
};

export type SiteAuditPageDetailViewModel = {
    url?: string | null;
    statusCode: number;
    results?: Array<SiteAuditResultDetailViewModel> | null;
};

export type SiteAuditResultDetailViewModel = {
    message?: string | null;
    checkId: number;
    isError: boolean;
    isWarning: boolean;
};

export type SitemapContentSettingsPostModel = {
    nodeKey: string;
    excludeFromSitemap: boolean;
    hideFromSitemap?: boolean | null;
    changeFrequency?: string | null;
    priority?: number | null;
};

export type SitemapContentSettingsViewModel = {
    excludeFromSitemap: boolean;
    changeFrequency?: string | null;
    priority?: number | null;
    inheritedChangeFrequency?: string | null;
    inheritedPriority?: number | null;
};

export type SitemapPageTypeSettingsPostModel = {
    contentTypeGuid: string;
    hideFromSitemap: boolean;
    changeFrequency?: string | null;
    priority?: number | null;
};

export type SitemapPageTypeSettingsViewModel = {
    hideFromSitemap: boolean;
    changeFrequency?: string | null;
    priority?: number | null;
};

export type SortScriptsPostModel = {
    keys?: Array<string> | null;
};

export type StopAuditPostModel = {
    id: number;
};

export type UmbracoDomainModel = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    readonly hasIdentity: boolean;
    domainName: string;
    readonly isWildcard: boolean;
    languageId?: number | null;
    languageIsoCode?: string | null;
    rootContentId?: number | null;
    sortOrder: number;
};

export type UpdateStatusCodesRedirectPostModel = {
    redirectIds?: Array<string> | null;
    redirectCode: number;
};

export type RobotsTxtSaveResponseModelWritable = {
    content?: string | null;
    errors?: Array<unknown> | null;
};

export type ScriptDefinitionViewModelWritable = {
    [key: string]: never;
};

export type UmbracoDomainModelWritable = {
    id: number;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: string | null;
    domainName: string;
    languageId?: number | null;
    languageIsoCode?: string | null;
    rootContentId?: number | null;
    sortOrder: number;
};

export type PostUmbracoSeoToolkitAiGenerateData = {
    body?: MetaFieldsAiGenerateRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitAI/generate';
};

export type PostUmbracoSeoToolkitAiGenerateResponses = {
    /**
     * OK
     */
    200: MetaFieldsAiGenerateResponseModel;
};

export type PostUmbracoSeoToolkitAiGenerateResponse = PostUmbracoSeoToolkitAiGenerateResponses[keyof PostUmbracoSeoToolkitAiGenerateResponses];

export type GetUmbracoSeoToolkitSchemaEntriesData = {
    body?: never;
    path?: never;
    query?: {
        ownerType?: string;
        ownerKey?: string;
    };
    url: '/umbraco/seoToolkit/schema/entries';
};

export type GetUmbracoSeoToolkitSchemaEntriesResponses = {
    /**
     * OK
     */
    200: Array<SchemaEntryViewModel>;
};

export type GetUmbracoSeoToolkitSchemaEntriesResponse = GetUmbracoSeoToolkitSchemaEntriesResponses[keyof GetUmbracoSeoToolkitSchemaEntriesResponses];

export type PostUmbracoSeoToolkitSchemaEntriesData = {
    body?: SchemaEntryPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/schema/entries';
};

export type PostUmbracoSeoToolkitSchemaEntriesResponses = {
    /**
     * OK
     */
    200: SchemaEntryViewModel;
};

export type PostUmbracoSeoToolkitSchemaEntriesResponse = PostUmbracoSeoToolkitSchemaEntriesResponses[keyof PostUmbracoSeoToolkitSchemaEntriesResponses];

export type DeleteUmbracoSeoToolkitSchemaEntriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/seoToolkit/schema/entries/{id}';
};

export type DeleteUmbracoSeoToolkitSchemaEntriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSchemaEntriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/seoToolkit/schema/entries/{id}';
};

export type GetUmbracoSeoToolkitSchemaEntriesByIdResponses = {
    /**
     * OK
     */
    200: SchemaEntryViewModel;
};

export type GetUmbracoSeoToolkitSchemaEntriesByIdResponse = GetUmbracoSeoToolkitSchemaEntriesByIdResponses[keyof GetUmbracoSeoToolkitSchemaEntriesByIdResponses];

export type PutUmbracoSeoToolkitSchemaEntriesByIdData = {
    body?: SchemaEntryPostModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/seoToolkit/schema/entries/{id}';
};

export type PutUmbracoSeoToolkitSchemaEntriesByIdResponses = {
    /**
     * OK
     */
    200: SchemaEntryViewModel;
};

export type PutUmbracoSeoToolkitSchemaEntriesByIdResponse = PutUmbracoSeoToolkitSchemaEntriesByIdResponses[keyof PutUmbracoSeoToolkitSchemaEntriesByIdResponses];

export type GetUmbracoSeoToolkitSchemaEntriesReusableData = {
    body?: never;
    path?: never;
    query?: {
        ownerType?: string;
        ownerKey?: string;
    };
    url: '/umbraco/seoToolkit/schema/entries/reusable';
};

export type GetUmbracoSeoToolkitSchemaEntriesReusableResponses = {
    /**
     * OK
     */
    200: Array<SchemaEntryViewModel>;
};

export type GetUmbracoSeoToolkitSchemaEntriesReusableResponse = GetUmbracoSeoToolkitSchemaEntriesReusableResponses[keyof GetUmbracoSeoToolkitSchemaEntriesReusableResponses];

export type GetUmbracoSeoToolkitSchemaTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/schema/types';
};

export type GetUmbracoSeoToolkitSchemaTypesResponses = {
    /**
     * OK
     */
    200: Array<SchemaTypeViewModel>;
};

export type GetUmbracoSeoToolkitSchemaTypesResponse = GetUmbracoSeoToolkitSchemaTypesResponses[keyof GetUmbracoSeoToolkitSchemaTypesResponses];

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/imagePreview';
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponse = GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses[keyof GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses];

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: never;
    path?: never;
    query?: {
        nodeGuid?: string;
        culture?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: MetaFieldsSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsPostViewModel;
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsAdditionalFields';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses = {
    /**
     * OK
     */
    200: Array<FieldItemViewModel>;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
    };
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: DocumentTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses];

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: DocumentTypeSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponse = GetUmbracoSeoToolkitNotFoundNotFoundResponses[keyof GetUmbracoSeoToolkitNotFoundNotFoundResponses];

export type PostUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        data?: string;
        domainId?: string;
    };
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type PostUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/domains';
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponses = {
    /**
     * OK
     */
    200: Array<DomainViewModel>;
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponse = GetUmbracoSeoToolkitRedirectsDomainsResponses[keyof GetUmbracoSeoToolkitRedirectsDomainsResponses];

export type GetUmbracoSeoToolkitRedirectsExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/export';
};

export type GetUmbracoSeoToolkitRedirectsExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/import';
};

export type PostUmbracoSeoToolkitRedirectsImportErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectData = {
    body?: DeleteRedirectsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: RedirectViewModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponse = GetUmbracoSeoToolkitRedirectsRedirectResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectResponses];

export type PostUmbracoSeoToolkitRedirectsRedirectData = {
    body?: SaveRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type PostUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
        orderBy?: string;
        orderDirection?: string;
        search?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirects';
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponses = {
    /**
     * OK
     */
    200: PagedRedirectListModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponse = GetUmbracoSeoToolkitRedirectsRedirectsResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectsResponses];

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesData = {
    body?: UpdateStatusCodesRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/updateStatusCodes';
};

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsValidateData = {
    body?: never;
    path?: never;
    query?: {
        fileExtension?: ImportRedirectsFileExtension;
        domain?: number;
        tempFileId?: string;
    };
    url: '/umbraco/seoToolkitRedirects/validate';
};

export type PostUmbracoSeoToolkitRedirectsValidateErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unprocessable Content
     */
    422: string;
};

export type PostUmbracoSeoToolkitRedirectsValidateError = PostUmbracoSeoToolkitRedirectsValidateErrors[keyof PostUmbracoSeoToolkitRedirectsValidateErrors];

export type PostUmbracoSeoToolkitRedirectsValidateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRobotsTxtData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type GetUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitRobotsTxtResponse = GetUmbracoSeoToolkitRobotsTxtResponses[keyof GetUmbracoSeoToolkitRobotsTxtResponses];

export type PostUmbracoSeoToolkitRobotsTxtData = {
    body?: RobotsTxtSavePostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type PostUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: RobotsTxtSaveResponseModel;
};

export type PostUmbracoSeoToolkitRobotsTxtResponse = PostUmbracoSeoToolkitRobotsTxtResponses[keyof PostUmbracoSeoToolkitRobotsTxtResponses];

export type GetUmbracoSeoToolkitScriptManagerDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/definitions';
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponses = {
    /**
     * OK
     */
    200: Array<ScriptDefinitionViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponse = GetUmbracoSeoToolkitScriptManagerDefinitionsResponses[keyof GetUmbracoSeoToolkitScriptManagerDefinitionsResponses];

export type DeleteUmbracoSeoToolkitScriptManagerScriptData = {
    body?: DeleteScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponse = DeleteUmbracoSeoToolkitScriptManagerScriptResponses[keyof DeleteUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponse = GetUmbracoSeoToolkitScriptManagerScriptResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptResponses];

export type PostUmbracoSeoToolkitScriptManagerScriptData = {
    body?: CreateScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponse = PostUmbracoSeoToolkitScriptManagerScriptResponses[keyof PostUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/scripts';
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponse = GetUmbracoSeoToolkitScriptManagerScriptsResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptsResponses];

export type PostUmbracoSeoToolkitScriptManagerSortScriptsData = {
    body?: SortScriptsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/sortScripts';
};

export type PostUmbracoSeoToolkitScriptManagerSortScriptsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/pageChecks';
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksResponses = {
    /**
     * OK
     */
    200: Array<SiteAuditCheckViewModel>;
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksResponse = GetUmbracoSeoToolkitSiteAuditPageChecksResponses[keyof GetUmbracoSeoToolkitSiteAuditPageChecksResponses];

export type PostUmbracoSeoToolkitSiteAuditRunData = {
    body?: RunPageCheckPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/run';
};

export type PostUmbracoSeoToolkitSiteAuditRunResponses = {
    /**
     * OK
     */
    200: SiteAuditDetailViewModel;
};

export type PostUmbracoSeoToolkitSiteAuditRunResponse = PostUmbracoSeoToolkitSiteAuditRunResponses[keyof PostUmbracoSeoToolkitSiteAuditRunResponses];

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: DeleteAuditsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: SiteAuditDetailViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type PostUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: CreateAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponse = PostUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof PostUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAuditConfiguration';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses = {
    /**
     * OK
     */
    200: SiteAuditCreateConfigViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudits';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses = {
    /**
     * OK
     */
    200: Array<SiteAuditOverviewViewModel>;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses];

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditData = {
    body?: StopAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/stopSiteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeGuid?: string;
    };
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: SitemapPageTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponse = GetUmbracoSeoToolkitSitemapSitemapSettingsResponses[keyof GetUmbracoSeoToolkitSitemapSitemapSettingsResponses];

export type PostUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: SitemapPageTypeSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type PostUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
    };
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: SitemapContentSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponse = GetUmbracoSeoToolkitSitemapContentContentSettingsResponses[keyof GetUmbracoSeoToolkitSitemapContentContentSettingsResponses];

export type PostUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body?: SitemapContentSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type PostUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body?: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body?: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSeoData = {
    body?: never;
    path?: never;
    query?: {
        contentGuid?: string;
        culture?: string;
    };
    url: '/api/seo';
};

export type GetApiSeoResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiSeoResponse = GetApiSeoResponses[keyof GetApiSeoResponses];
