// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUmbracoSeoToolkitDomainsDeleteData, DeleteUmbracoSeoToolkitDomainsDeleteResponses, GetUmbracoSeoToolkitDomainsConfigData, GetUmbracoSeoToolkitDomainsConfigResponses, GetUmbracoSeoToolkitDomainsGetData, GetUmbracoSeoToolkitDomainsGetPredefinedData, GetUmbracoSeoToolkitDomainsGetPredefinedResponses, GetUmbracoSeoToolkitDomainsGetResponses, GetUmbracoSeoToolkitIsEnabledData, GetUmbracoSeoToolkitIsEnabledResponses, GetUmbracoSeoToolkitModulesData, GetUmbracoSeoToolkitModulesResponses, GetUmbracoSeoToolkitSeoKeyValueSettingsData, GetUmbracoSeoToolkitSeoKeyValueSettingsResponses, GetUmbracoSeoToolkitSeoKeyValueSettingsValueData, GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses, GetUmbracoSeoToolkitSettingsIsAiAvailableData, GetUmbracoSeoToolkitSettingsIsAiAvailableResponses, GetUmbracoSeoToolkitSettingsSeoSettingsData, GetUmbracoSeoToolkitSettingsSeoSettingsResponses, GetUmbracoSeoToolkitSitemapContentContentSettingsData, GetUmbracoSeoToolkitSitemapContentContentSettingsResponses, GetUmbracoSeoToolkitSitemapSitemapSettingsData, GetUmbracoSeoToolkitSitemapSitemapSettingsResponses, GetUmbracoSeoToolkitTreeInfoAncestorsData, GetUmbracoSeoToolkitTreeInfoAncestorsResponses, GetUmbracoSeoToolkitTreeInfoChildrenData, GetUmbracoSeoToolkitTreeInfoChildrenResponses, GetUmbracoSeoToolkitTreeInfoRootData, GetUmbracoSeoToolkitTreeInfoRootResponses, PostUmbracoSeoToolkitDomainsSaveData, PostUmbracoSeoToolkitDomainsSaveResponses, PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData, PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses, PostUmbracoSeoToolkitSettingsSeoSettingsData, PostUmbracoSeoToolkitSettingsSeoSettingsResponses, PostUmbracoSeoToolkitSitemapContentContentSettingsData, PostUmbracoSeoToolkitSitemapContentContentSettingsResponses, PostUmbracoSeoToolkitSitemapSitemapSettingsData, PostUmbracoSeoToolkitSitemapSitemapSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BackofficeSeoToolkit {
    public static getUmbracoSeoToolkitIsEnabled<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitIsEnabledData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitIsEnabledResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkit/isEnabled', ...options });
    }
    
    public static getUmbracoSeoToolkitModules<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitModulesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitModulesResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkit/modules', ...options });
    }
    
    public static getUmbracoSeoToolkitTreeInfoAncestors<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitTreeInfoAncestorsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitTreeInfoAncestorsResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkit/tree/info/ancestors', ...options });
    }
    
    public static getUmbracoSeoToolkitTreeInfoChildren<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitTreeInfoChildrenData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitTreeInfoChildrenResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkit/tree/info/children', ...options });
    }
    
    public static getUmbracoSeoToolkitTreeInfoRoot<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitTreeInfoRootData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitTreeInfoRootResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkit/tree/info/root', ...options });
    }
    
    public static getUmbracoSeoToolkitDomainsConfig<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitDomainsConfigData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitDomainsConfigResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitDomains/config', ...options });
    }
    
    public static deleteUmbracoSeoToolkitDomainsDelete<ThrowOnError extends boolean = true>(options?: Options<DeleteUmbracoSeoToolkitDomainsDeleteData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoSeoToolkitDomainsDeleteResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitDomains/delete', ...options });
    }
    
    public static getUmbracoSeoToolkitDomainsGet<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitDomainsGetData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitDomainsGetResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitDomains/get', ...options });
    }
    
    public static getUmbracoSeoToolkitDomainsGetPredefined<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitDomainsGetPredefinedData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitDomainsGetPredefinedResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitDomains/getPredefined', ...options });
    }
    
    public static postUmbracoSeoToolkitDomainsSave<ThrowOnError extends boolean = true>(options: Options<PostUmbracoSeoToolkitDomainsSaveData, ThrowOnError>) {
        return (options.client ?? client).post<PostUmbracoSeoToolkitDomainsSaveResponses, unknown, ThrowOnError>({
            url: '/umbraco/seoToolkitDomains/save',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getUmbracoSeoToolkitSeoKeyValueSettings<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSeoKeyValueSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSeoKeyValueSettingsResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSeoKeyValueSettings', ...options });
    }
    
    public static postUmbracoSeoToolkitSeoKeyValueSettingsSave<ThrowOnError extends boolean = true>(options: Options<PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData, ThrowOnError>) {
        return (options.client ?? client).post<PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses, unknown, ThrowOnError>({
            url: '/umbraco/seoToolkitSeoKeyValueSettings/save',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getUmbracoSeoToolkitSeoKeyValueSettingsValue<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSeoKeyValueSettingsValueData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSeoKeyValueSettings/value', ...options });
    }
    
    public static getUmbracoSeoToolkitSettingsIsAiAvailable<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSettingsIsAiAvailableData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSettingsIsAiAvailableResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSettings/isAIAvailable', ...options });
    }
    
    public static getUmbracoSeoToolkitSettingsSeoSettings<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSettingsSeoSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSettingsSeoSettingsResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSettings/seoSettings', ...options });
    }
    
    public static postUmbracoSeoToolkitSettingsSeoSettings<ThrowOnError extends boolean = true>(options: Options<PostUmbracoSeoToolkitSettingsSeoSettingsData, ThrowOnError>) {
        return (options.client ?? client).post<PostUmbracoSeoToolkitSettingsSeoSettingsResponses, unknown, ThrowOnError>({
            url: '/umbraco/seoToolkitSettings/seoSettings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class BackofficeSeoToolkitSitemap {
    public static getUmbracoSeoToolkitSitemapSitemapSettings<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSitemapSitemapSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSitemapSitemapSettingsResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSitemap/sitemapSettings', ...options });
    }
    
    public static postUmbracoSeoToolkitSitemapSitemapSettings<ThrowOnError extends boolean = true>(options: Options<PostUmbracoSeoToolkitSitemapSitemapSettingsData, ThrowOnError>) {
        return (options.client ?? client).post<PostUmbracoSeoToolkitSitemapSitemapSettingsResponses, unknown, ThrowOnError>({
            url: '/umbraco/seoToolkitSitemap/sitemapSettings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getUmbracoSeoToolkitSitemapContentContentSettings<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoSeoToolkitSitemapContentContentSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoSeoToolkitSitemapContentContentSettingsResponses, unknown, ThrowOnError>({ url: '/umbraco/seoToolkitSitemapContent/contentSettings', ...options });
    }
    
    public static postUmbracoSeoToolkitSitemapContentContentSettings<ThrowOnError extends boolean = true>(options: Options<PostUmbracoSeoToolkitSitemapContentContentSettingsData, ThrowOnError>) {
        return (options.client ?? client).post<PostUmbracoSeoToolkitSitemapContentContentSettingsResponses, unknown, ThrowOnError>({
            url: '/umbraco/seoToolkitSitemapContent/contentSettings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
