// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441/' | (string & {});
};

export type SitemapPageTypeSettingsViewModel = {
    hideFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SitemapPageTypeSettingsPostModel = {
    contentTypeGuid: string;
    hideFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SitemapContentSettingsViewModel = {
    excludeFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
    inheritedChangeFrequency?: null | string;
    inheritedPriority?: null | number | string;
};

export type SitemapContentSettingsPostModel = {
    nodeKey: string;
    excludeFromSitemap: boolean;
    hideFromSitemap?: null | boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SeoToolkitTreeItemApiModel = {
    id: string;
    name: string;
    parentId?: null | string;
    isDraft: boolean;
    hasChildren: boolean;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoDomainConfigViewModel = {
    domains: Array<IDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type IDomainModel = {
    domainName: string;
    isWildcard: boolean;
    languageId?: null | number | string;
    languageIsoCode?: null | string;
    rootContentId?: null | number | string;
    sortOrder: number | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type SeoDomainCollection = {
    id?: null | string;
    name: string;
    baseUrl?: null | string;
    domainIds: Array<number | string>;
    settings: {
        [key: string]: string;
    };
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number | string;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number | string;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeGuid?: string;
    };
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: SitemapPageTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponse = GetUmbracoSeoToolkitSitemapSitemapSettingsResponses[keyof GetUmbracoSeoToolkitSitemapSitemapSettingsResponses];

export type PostUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body: SitemapPageTypeSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type PostUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
    };
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: SitemapContentSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponse = GetUmbracoSeoToolkitSitemapContentContentSettingsResponses[keyof GetUmbracoSeoToolkitSitemapContentContentSettingsResponses];

export type PostUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body: SitemapContentSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type PostUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};
