// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoSeoToolkitModulesResponse, GetUmbracoSeoToolkitRobotsTxtResponse, PostUmbracoSeoToolkitRobotsTxtData, PostUmbracoSeoToolkitRobotsTxtResponse, GetUmbracoSeoToolkitTreeInfoAncestorsData, GetUmbracoSeoToolkitTreeInfoAncestorsResponse, GetUmbracoSeoToolkitTreeInfoChildrenData, GetUmbracoSeoToolkitTreeInfoChildrenResponse, GetUmbracoSeoToolkitTreeInfoRootData, GetUmbracoSeoToolkitTreeInfoRootResponse, GetUmbracoSeoToolkitScriptManagerDefinitionsResponse, DeleteUmbracoSeoToolkitScriptManagerScriptData, DeleteUmbracoSeoToolkitScriptManagerScriptResponse, GetUmbracoSeoToolkitScriptManagerScriptData, GetUmbracoSeoToolkitScriptManagerScriptResponse, PostUmbracoSeoToolkitScriptManagerScriptData, PostUmbracoSeoToolkitScriptManagerScriptResponse, GetUmbracoSeoToolkitScriptManagerScriptsResponse } from './types.gen';

export class SeoToolkitService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitModules(): CancelablePromise<GetUmbracoSeoToolkitModulesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/modules'
        });
    }
    
    /**
     * @returns string OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitRobotsTxt(): CancelablePromise<GetUmbracoSeoToolkitRobotsTxtResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/robotsTxt'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postUmbracoSeoToolkitRobotsTxt(data: PostUmbracoSeoToolkitRobotsTxtData = {}): CancelablePromise<PostUmbracoSeoToolkitRobotsTxtResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/seoToolkit/robotsTxt',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.descendantId
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitTreeInfoAncestors(data: GetUmbracoSeoToolkitTreeInfoAncestorsData = {}): CancelablePromise<GetUmbracoSeoToolkitTreeInfoAncestorsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/tree/info/ancestors',
            query: {
                descendantId: data.descendantId
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.parentId
     * @param data.skip
     * @param data.take
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitTreeInfoChildren(data: GetUmbracoSeoToolkitTreeInfoChildrenData = {}): CancelablePromise<GetUmbracoSeoToolkitTreeInfoChildrenResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/tree/info/children',
            query: {
                parentId: data.parentId,
                skip: data.skip,
                take: data.take
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.skip
     * @param data.take
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitTreeInfoRoot(data: GetUmbracoSeoToolkitTreeInfoRootData = {}): CancelablePromise<GetUmbracoSeoToolkitTreeInfoRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/tree/info/root',
            query: {
                skip: data.skip,
                take: data.take
            }
        });
    }
    
}

export class SeoToolkitScriptManagerService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitScriptManagerDefinitions(): CancelablePromise<GetUmbracoSeoToolkitScriptManagerDefinitionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkitScriptManager/definitions'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static deleteUmbracoSeoToolkitScriptManagerScript(data: DeleteUmbracoSeoToolkitScriptManagerScriptData = {}): CancelablePromise<DeleteUmbracoSeoToolkitScriptManagerScriptResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/umbraco/seoToolkitScriptManager/script',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitScriptManagerScript(data: GetUmbracoSeoToolkitScriptManagerScriptData = {}): CancelablePromise<GetUmbracoSeoToolkitScriptManagerScriptResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkitScriptManager/script',
            query: {
                id: data.id
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static postUmbracoSeoToolkitScriptManagerScript(data: PostUmbracoSeoToolkitScriptManagerScriptData = {}): CancelablePromise<PostUmbracoSeoToolkitScriptManagerScriptResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/seoToolkitScriptManager/script',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitScriptManagerScripts(): CancelablePromise<GetUmbracoSeoToolkitScriptManagerScriptsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkitScriptManager/scripts'
        });
    }
    
}