// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441/' | (string & {});
};

export type SortScriptsPostModel = {
    keys?: null | Array<string>;
};

export type SeoToolkitTreeItemApiModel = {
    id: string;
    name: string;
    parentId?: null | string;
    isDraft: boolean;
    hasChildren: boolean;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoDomainConfigViewModel = {
    domains: Array<IDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type IDomainModel = {
    domainName: string;
    isWildcard: boolean;
    languageId?: null | number | string;
    languageIsoCode?: null | string;
    rootContentId?: null | number | string;
    sortOrder: number | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type SeoDomainCollection = {
    id?: null | string;
    name: string;
    baseUrl?: null | string;
    domainIds: Array<number | string>;
    settings: {
        [key: string]: string;
    };
};

export type ScriptListViewModel = {
    id: string;
    name?: null | string;
    definitionName?: null | string;
    sortOrder: number | string;
};

export type ScriptField = {
    key?: null | string;
    name?: null | string;
    description?: null | string;
    propertyAlias?: null | string;
};

export type ScriptDetailViewModel = {
    id: number | string;
    key?: null | string;
    name?: null | string;
    definitionAlias?: null | string;
    config?: null | {
        [key: string]: string;
    };
    domainId?: null | string;
    sortOrder: number | string;
};

export type ScriptDefinitionViewModel = {
    name?: null | string;
    alias?: null | string;
    fields?: null | Array<ScriptField>;
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number | string;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type DeleteScriptPostModel = {
    ids?: null | Array<string>;
};

export type CreateScriptPostModel = {
    id: number | string;
    key?: null | string;
    name: null | string;
    definitionAlias: null | string;
    fields?: null | {
        [key: string]: string;
    };
    domainId?: null | string;
    sortOrder?: null | number | string;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number | string;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/definitions';
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponses = {
    /**
     * OK
     */
    200: Array<ScriptDefinitionViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponse = GetUmbracoSeoToolkitScriptManagerDefinitionsResponses[keyof GetUmbracoSeoToolkitScriptManagerDefinitionsResponses];

export type DeleteUmbracoSeoToolkitScriptManagerScriptData = {
    body: DeleteScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponse = DeleteUmbracoSeoToolkitScriptManagerScriptResponses[keyof DeleteUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponse = GetUmbracoSeoToolkitScriptManagerScriptResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptResponses];

export type PostUmbracoSeoToolkitScriptManagerScriptData = {
    body: CreateScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponse = PostUmbracoSeoToolkitScriptManagerScriptResponses[keyof PostUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/scripts';
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponse = GetUmbracoSeoToolkitScriptManagerScriptsResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptsResponses];

export type PostUmbracoSeoToolkitScriptManagerSortScriptsData = {
    body: SortScriptsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/sortScripts';
};

export type PostUmbracoSeoToolkitScriptManagerSortScriptsResponses = {
    /**
     * OK
     */
    200: unknown;
};
