// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441/' | (string & {});
};

export type UpdateStatusCodesRedirectPostModel = {
    redirectIds?: null | Array<string>;
    redirectCode: number | string;
};

export type SeoToolkitTreeItemApiModel = {
    id: string;
    name: string;
    parentId?: null | string;
    isDraft: boolean;
    hasChildren: boolean;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoDomainConfigViewModel = {
    domains: Array<IDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type IDomainModel = {
    domainName: string;
    isWildcard: boolean;
    languageId?: null | number | string;
    languageIsoCode?: null | string;
    rootContentId?: null | number | string;
    sortOrder: number | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type SeoDomainCollection = {
    id?: null | string;
    name: string;
    baseUrl?: null | string;
    domainIds: Array<number | string>;
    settings: {
        [key: string]: string;
    };
};

export type SaveRedirectPostModel = {
    id: number | string;
    key?: null | string;
    domain?: null | number | string;
    customDomain?: null | string;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: null | string;
    newUrl?: null | string;
    newNodeId?: null | string;
    newCultureId?: null | string;
    redirectCode: number | string;
};

export type RedirectViewModel = {
    id: number | string;
    key: string;
    domain?: null | number | string;
    customDomain?: null | string;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: null | string;
    newUrl?: null | string;
    newNodeId?: null | string;
    newCultureIso?: null | string;
    redirectCode: number | string;
    lastUpdated?: null | string;
};

export type RedirectListViewModel = {
    key: string;
    isEnabled: boolean;
    domain?: null | string;
    oldUrl?: null | string;
    newUrl?: null | string;
    statusCode: number | string;
    lastUpdated?: null | string;
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number | string;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type PagedRedirectListModel = {
    total: number | string;
    items: Array<RedirectListViewModel>;
};

export type ImportRedirectsFileExtension = number;

export type DomainViewModel = {
    id: number | string;
    name?: null | string;
};

export type DeleteRedirectsPostModel = {
    ids?: null | Array<string>;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number | string;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/domains';
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponses = {
    /**
     * OK
     */
    200: Array<DomainViewModel>;
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponse = GetUmbracoSeoToolkitRedirectsDomainsResponses[keyof GetUmbracoSeoToolkitRedirectsDomainsResponses];

export type GetUmbracoSeoToolkitRedirectsExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/export';
};

export type GetUmbracoSeoToolkitRedirectsExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/import';
};

export type PostUmbracoSeoToolkitRedirectsImportErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectData = {
    body: DeleteRedirectsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: RedirectViewModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponse = GetUmbracoSeoToolkitRedirectsRedirectResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectResponses];

export type PostUmbracoSeoToolkitRedirectsRedirectData = {
    body: SaveRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type PostUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number | string;
        pageSize?: number | string;
        orderBy?: string;
        orderDirection?: string;
        search?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirects';
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponses = {
    /**
     * OK
     */
    200: PagedRedirectListModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponse = GetUmbracoSeoToolkitRedirectsRedirectsResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectsResponses];

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesData = {
    body: UpdateStatusCodesRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/updateStatusCodes';
};

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsValidateData = {
    body?: never;
    path?: never;
    query?: {
        fileExtension?: ImportRedirectsFileExtension;
        domain?: number | string;
        tempFileId?: string;
    };
    url: '/umbraco/seoToolkitRedirects/validate';
};

export type PostUmbracoSeoToolkitRedirectsValidateErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unprocessable Entity
     */
    422: string;
};

export type PostUmbracoSeoToolkitRedirectsValidateError = PostUmbracoSeoToolkitRedirectsValidateErrors[keyof PostUmbracoSeoToolkitRedirectsValidateErrors];

export type PostUmbracoSeoToolkitRedirectsValidateResponses = {
    /**
     * OK
     */
    200: unknown;
};
