<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Product>SeoToolkit uSync</Product>
    <PackageId>SeoToolkit.Umbraco.uSync</PackageId>
    <Title>SeoToolkit uSync</Title>
    <Description>Connectors to export/import SeoToolkit settings with uSync</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>umbraco plugin package</PackageTags>
    <RootNamespace>SeoToolkit.Umbraco.uSync</RootNamespace>
    <PackageProjectUrl>https://github.com/patrickdemooij9/SeoToolkit.Umbraco</PackageProjectUrl>
    <RepositoryUrl>https://github.com/patrickdemooij9/SeoToolkit.Umbraco</RepositoryUrl>
    <PackageIconUrl>https://raw.githubusercontent.com/patrickdemooij9/SeoToolkit.Umbraco/main/package/SeoToolkitIcon.png</PackageIconUrl>
    <Version>1.0.0-beta1</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="uSync.BackOffice" Version="17.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SeoToolkit.Umbraco\SeoToolkit.Umbraco.csproj" />
  </ItemGroup>

</Project>
