// This file is auto-generated by @hey-api/openapi-ts

export const NamedEntityTreeItemResponseModelSchema = {
    required: ['hasChildren', 'id', 'name'],
    type: 'object',
    properties: {
        hasChildren: {
            type: 'boolean'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        parent: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ReferenceByIdModel'
                }
            ],
            nullable: true
        },
        name: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const PagedNamedEntityTreeItemResponseModelSchema = {
    required: ['items', 'total'],
    type: 'object',
    properties: {
        total: {
            type: 'integer',
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/NamedEntityTreeItemResponseModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const ReferenceByIdModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleSchema = {
    required: ['alias', 'icon', 'link', 'status', 'title'],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        alias: {
            type: 'string'
        },
        icon: {
            type: 'string'
        },
        link: {
            type: 'string'
        },
        status: {
            '$ref': '#/components/schemas/SeoToolkitModuleStatus'
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleStatusSchema = {
    enum: ['NotInstalled', 'Installed', 'Disabled'],
    type: 'string'
} as const;