// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoSeoToolkitModulesResponse, GetUmbracoSeoToolkitTreeInfoRootData, GetUmbracoSeoToolkitTreeInfoRootResponse } from './types.gen';

export class SeoToolkitService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitModules(): CancelablePromise<GetUmbracoSeoToolkitModulesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/modules'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.skip
     * @param data.take
     * @returns unknown OK
     * @throws ApiError
     */
    public static getUmbracoSeoToolkitTreeInfoRoot(data: GetUmbracoSeoToolkitTreeInfoRootData = {}): CancelablePromise<GetUmbracoSeoToolkitTreeInfoRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/seoToolkit/tree/info/root',
            query: {
                skip: data.skip,
                take: data.take
            }
        });
    }
    
}