// This file is auto-generated by @hey-api/openapi-ts

export type NamedEntityTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ((ReferenceByIdModel) | null);
    name: string;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<(NamedEntityTreeItemResponseModel)>;
};

export type ReferenceByIdModel = {
    id: string;
};

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoToolkitModuleStatus = 'NotInstalled' | 'Installed' | 'Disabled';

export const SeoToolkitModuleStatus = {
    NOT_INSTALLED: 'NotInstalled',
    INSTALLED: 'Installed',
    DISABLED: 'Disabled'
} as const;

export type GetUmbracoSeoToolkitModulesResponse = (Array<(SeoToolkitModule)>);

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    skip?: number;
    take?: number;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = ((PagedNamedEntityTreeItemResponseModel));