// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:57441/' | (string & {});
};

export type CreateAuditPostModel = {
    name: null | string;
    selectedNodeId: string;
    checks?: null | Array<number | string>;
    startAudit: boolean;
    maxPagesToCrawl: number | string;
    delayBetweenRequests: number | string;
};

export type CreateScriptPostModel = {
    id: number | string;
    key?: null | string;
    name: null | string;
    definitionAlias: null | string;
    fields?: null | {
        [key: string]: string;
    };
    domainId?: null | string;
    sortOrder?: null | number | string;
};

export type DeleteAuditsPostModel = {
    ids?: null | Array<number | string>;
};

export type DeleteRedirectsPostModel = {
    ids?: null | Array<string>;
};

export type DeleteScriptPostModel = {
    ids?: null | Array<string>;
};

export type DocumentTypeSettingsContentViewModel = {
    fields?: null | Array<SeoFieldViewModel>;
    inheritance?: DocumentTypeSettingsInheritanceViewModel;
};

export type DocumentTypeSettingsInheritanceViewModel = {
    id?: null | string;
};

export type DocumentTypeSettingsPostViewModel = {
    nodeId: string;
    enableSeoSettings: boolean;
    fields?: null | {
        [key: string]: DocumentTypeValuePostViewModel;
    };
    inheritanceId?: null | string;
};

export type DocumentTypeSettingsViewModel = {
    contentModel?: DocumentTypeSettingsContentViewModel;
};

export type DocumentTypeValuePostViewModel = {
    useInheritedValue: boolean;
    value?: unknown;
};

export type DomainViewModel = {
    id: number | string;
    name?: null | string;
};

export type FieldItemViewModel = {
    name: null | string;
    value: null | string;
    onlyShowIfInherited: boolean;
};

export type FieldPreviewerViewModel = {
    group?: null | string;
    view?: null | string;
};

export type IDomainModel = {
    domainName: string;
    isWildcard: boolean;
    languageId?: null | number | string;
    languageIsoCode?: null | string;
    rootContentId?: null | number | string;
    sortOrder: number | string;
    id: number | string;
    key: string;
    createDate: string;
    updateDate: string;
    deleteDate?: null | string;
    hasIdentity: boolean;
};

export type ImportRedirectsFileExtension = number;

export type MetaFieldsAiFieldSuggestion = {
    alias: string;
    value: string;
};

export type MetaFieldsAiGenerateRequestModel = {
    nodeId: string;
    culture?: null | string;
};

export type MetaFieldsAiGenerateResponseModel = {
    suggestions: Array<MetaFieldsAiFieldSuggestion>;
};

export type MetaFieldsSettingsPostViewModel = {
    nodeId: string;
    culture?: null | string;
    userValues?: null | {
        [key: string]: unknown;
    };
};

export type MetaFieldsSettingsViewModel = {
    fields?: null | Array<SeoSettingsFieldViewModel>;
    groups?: null | Array<SeoFieldGroupViewModel>;
    previewers?: null | Array<FieldPreviewerViewModel>;
    seoEnabled: boolean;
};

export type PagedRedirectListModel = {
    total: number | string;
    items: Array<RedirectListViewModel>;
};

export type PagedSeoToolkitTreeItemApiModel = {
    total: number | string;
    items: Array<SeoToolkitTreeItemApiModel>;
};

export type RedirectListViewModel = {
    key: string;
    isEnabled: boolean;
    domain?: null | string;
    oldUrl?: null | string;
    newUrl?: null | string;
    statusCode: number | string;
    lastUpdated?: null | string;
};

export type RedirectViewModel = {
    id: number | string;
    key: string;
    domain?: null | number | string;
    customDomain?: null | string;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: null | string;
    newUrl?: null | string;
    newNodeId?: null | string;
    newCultureIso?: null | string;
    redirectCode: number | string;
    lastUpdated?: null | string;
};

export type RobotsTxtSavePostModel = {
    skipValidation: boolean;
    content?: null | string;
    domainId?: null | string;
};

export type RobotsTxtSaveResponseModel = {
    content?: null | string;
    errors?: null | Array<RobotsTxtValidationViewModel>;
};

export type RobotsTxtValidationViewModel = {
    lineNumber: number | string;
    error?: null | string;
};

export type RunPageCheckPostModel = {
    contentId: string;
};

export type SaveRedirectPostModel = {
    id: number | string;
    key?: null | string;
    domain?: null | number | string;
    customDomain?: null | string;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: null | string;
    newUrl?: null | string;
    newNodeId?: null | string;
    newCultureId?: null | string;
    redirectCode: number | string;
};

export type ScriptDefinitionViewModel = {
    name?: null | string;
    alias?: null | string;
    fields?: null | Array<ScriptField>;
};

export type ScriptDetailViewModel = {
    id: number | string;
    key?: null | string;
    name?: null | string;
    definitionAlias?: null | string;
    config?: null | {
        [key: string]: string;
    };
    domainId?: null | string;
    sortOrder: number | string;
};

export type ScriptField = {
    key?: null | string;
    name?: null | string;
    description?: null | string;
    propertyAlias?: null | string;
};

export type ScriptListViewModel = {
    id: string;
    name?: null | string;
    definitionName?: null | string;
    sortOrder: number | string;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoDomainCollection = {
    id?: null | string;
    name: string;
    baseUrl?: null | string;
    domainIds: Array<number | string>;
    settings: {
        [key: string]: string;
    };
};

export type SeoDomainConfigViewModel = {
    domains: Array<IDomainModel>;
    moduleSettings: Array<SeoDomainModuleSettingViewModel>;
};

export type SeoDomainModuleSettingViewModel = {
    id: string;
    name: string;
};

export type SeoFieldEditorViewModel = {
    view?: null | string;
    config?: null | {
        [key: string]: unknown;
    };
};

export type SeoFieldGroupViewModel = {
    alias?: null | string;
    name?: null | string;
    description?: null | string;
};

export type SeoFieldViewModel = {
    alias?: null | string;
    title?: null | string;
    description?: null | string;
    useInheritedValue: boolean;
    value?: unknown;
    editor?: SeoFieldEditorViewModel;
};

export type SeoKeyValueSettingViewModel = {
    key: string;
    title: string;
    description: string;
    propertyAlias: string;
    value?: unknown;
    isRoot: boolean;
};

export type SeoKeyValueViewModel = {
    key: string;
    value: string;
};

export type SeoSettingsFieldViewModel = {
    alias?: null | string;
    title?: null | string;
    description?: null | string;
    groupAlias?: null | string;
    suggestions?: null | Array<SeoSuggestionViewModel>;
    value?: null | string;
    userValue?: unknown;
    editView?: null | string;
    editConfig?: null | {
        [key: string]: unknown;
    };
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoSuggestionViewModel = {
    alias?: null | string;
    config?: null | {
        [key: string]: unknown;
    };
};

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SeoToolkitTreeItemApiModel = {
    id: string;
    name: string;
    parentId?: null | string;
    isDraft: boolean;
    hasChildren: boolean;
};

export type SiteAuditCheckViewModel = {
    id: number | string;
    name?: null | string;
    description?: null | string;
    errorMessage?: null | string;
};

export type SiteAuditCreateConfigViewModel = {
    checks?: null | Array<SiteAuditCheckViewModel>;
    minimumDelayBetweenRequest: number | string;
    allowMinimumDelayBetweenRequestSetting: boolean;
};

export type SiteAuditDetailViewModel = {
    id: number | string;
    name?: null | string;
    maxPagesToCrawl?: null | number | string;
    totalPagesFound: number | string;
    progress: number | string;
    status?: null | string;
    checks?: null | Array<SiteAuditCheckViewModel>;
    pagesCrawled?: null | Array<SiteAuditPageDetailViewModel>;
};

export type SiteAuditOverviewViewModel = {
    id: number | string;
    name?: null | string;
    createdDate?: null | string;
    status?: null | string;
};

export type SiteAuditPageDetailViewModel = {
    url?: null | string;
    statusCode: number | string;
    results?: null | Array<SiteAuditResultDetailViewModel>;
};

export type SiteAuditResultDetailViewModel = {
    message?: null | string;
    checkId: number | string;
    isError: boolean;
    isWarning: boolean;
};

export type SitemapContentSettingsPostModel = {
    nodeKey: string;
    excludeFromSitemap: boolean;
    hideFromSitemap?: null | boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SitemapContentSettingsViewModel = {
    excludeFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
    inheritedChangeFrequency?: null | string;
    inheritedPriority?: null | number | string;
};

export type SitemapPageTypeSettingsPostModel = {
    contentTypeGuid: string;
    hideFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SitemapPageTypeSettingsViewModel = {
    hideFromSitemap: boolean;
    changeFrequency?: null | string;
    priority?: null | number | string;
};

export type SortScriptsPostModel = {
    keys?: null | Array<string>;
};

export type StopAuditPostModel = {
    id: number | string;
};

export type UpdateStatusCodesRedirectPostModel = {
    redirectIds?: null | Array<string>;
    redirectCode: number | string;
};

export type GetUmbracoSeoToolkitIsEnabledData = {
    body?: never;
    path?: never;
    query?: {
        moduleAlias?: string;
    };
    url: '/umbraco/seoToolkit/isEnabled';
};

export type GetUmbracoSeoToolkitIsEnabledResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitIsEnabledResponse = GetUmbracoSeoToolkitIsEnabledResponses[keyof GetUmbracoSeoToolkitIsEnabledResponses];

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitTreeItemApiModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentUnique?: string;
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number | string;
        take?: number | string;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedSeoToolkitTreeItemApiModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitDomainsConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/config';
};

export type GetUmbracoSeoToolkitDomainsConfigResponses = {
    /**
     * OK
     */
    200: SeoDomainConfigViewModel;
};

export type GetUmbracoSeoToolkitDomainsConfigResponse = GetUmbracoSeoToolkitDomainsConfigResponses[keyof GetUmbracoSeoToolkitDomainsConfigResponses];

export type DeleteUmbracoSeoToolkitDomainsDeleteData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/delete';
};

export type DeleteUmbracoSeoToolkitDomainsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitDomainsGetData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitDomains/get';
};

export type GetUmbracoSeoToolkitDomainsGetResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetResponse = GetUmbracoSeoToolkitDomainsGetResponses[keyof GetUmbracoSeoToolkitDomainsGetResponses];

export type GetUmbracoSeoToolkitDomainsGetPredefinedData = {
    body?: never;
    path?: never;
    query?: {
        umbracoDomainId?: number | string;
    };
    url: '/umbraco/seoToolkitDomains/getPredefined';
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponses = {
    /**
     * OK
     */
    200: SeoDomainCollection;
};

export type GetUmbracoSeoToolkitDomainsGetPredefinedResponse = GetUmbracoSeoToolkitDomainsGetPredefinedResponses[keyof GetUmbracoSeoToolkitDomainsGetPredefinedResponses];

export type PostUmbracoSeoToolkitDomainsSaveData = {
    body: SeoDomainCollection;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitDomains/save';
};

export type PostUmbracoSeoToolkitDomainsSaveResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostUmbracoSeoToolkitDomainsSaveResponse = PostUmbracoSeoToolkitDomainsSaveResponses[keyof PostUmbracoSeoToolkitDomainsSaveResponses];

export type GetUmbracoSeoToolkitSeoKeyValueSettingsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponses = {
    /**
     * OK
     */
    200: Array<SeoKeyValueSettingViewModel>;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsResponses];

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveData = {
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/save';
};

export type PostUmbracoSeoToolkitSeoKeyValueSettingsSaveResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueData = {
    body?: never;
    path?: never;
    query?: {
        key?: string;
    };
    url: '/umbraco/seoToolkitSeoKeyValueSettings/value';
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses = {
    /**
     * OK
     */
    200: SeoKeyValueViewModel;
};

export type GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponse = GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses[keyof GetUmbracoSeoToolkitSeoKeyValueSettingsValueResponses];

export type GetUmbracoSeoToolkitSettingsIsAiAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/isAIAvailable';
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetUmbracoSeoToolkitSettingsIsAiAvailableResponse = GetUmbracoSeoToolkitSettingsIsAiAvailableResponses[keyof GetUmbracoSeoToolkitSettingsIsAiAvailableResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitAiGenerateData = {
    body: MetaFieldsAiGenerateRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitAI/generate';
};

export type PostUmbracoSeoToolkitAiGenerateResponses = {
    /**
     * OK
     */
    200: MetaFieldsAiGenerateResponseModel;
};

export type PostUmbracoSeoToolkitAiGenerateResponse = PostUmbracoSeoToolkitAiGenerateResponses[keyof PostUmbracoSeoToolkitAiGenerateResponses];

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/imagePreview';
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponse = GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses[keyof GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses];

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: never;
    path?: never;
    query?: {
        nodeGuid?: string;
        culture?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body: MetaFieldsSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsPostViewModel;
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsAdditionalFields';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses = {
    /**
     * OK
     */
    200: Array<FieldItemViewModel>;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
    };
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: DocumentTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses];

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body: DocumentTypeSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponse = GetUmbracoSeoToolkitNotFoundNotFoundResponses[keyof GetUmbracoSeoToolkitNotFoundNotFoundResponses];

export type PostUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        data?: string;
        domainId?: string;
    };
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type PostUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/domains';
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponses = {
    /**
     * OK
     */
    200: Array<DomainViewModel>;
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponse = GetUmbracoSeoToolkitRedirectsDomainsResponses[keyof GetUmbracoSeoToolkitRedirectsDomainsResponses];

export type GetUmbracoSeoToolkitRedirectsExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/export';
};

export type GetUmbracoSeoToolkitRedirectsExportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/import';
};

export type PostUmbracoSeoToolkitRedirectsImportErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectData = {
    body: DeleteRedirectsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: RedirectViewModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponse = GetUmbracoSeoToolkitRedirectsRedirectResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectResponses];

export type PostUmbracoSeoToolkitRedirectsRedirectData = {
    body: SaveRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type PostUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number | string;
        pageSize?: number | string;
        orderBy?: string;
        orderDirection?: string;
        search?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirects';
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponses = {
    /**
     * OK
     */
    200: PagedRedirectListModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponse = GetUmbracoSeoToolkitRedirectsRedirectsResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectsResponses];

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesData = {
    body: UpdateStatusCodesRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/updateStatusCodes';
};

export type PostUmbracoSeoToolkitRedirectsUpdateStatusCodesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoSeoToolkitRedirectsValidateData = {
    body?: never;
    path?: never;
    query?: {
        fileExtension?: ImportRedirectsFileExtension;
        domain?: number | string;
        tempFileId?: string;
    };
    url: '/umbraco/seoToolkitRedirects/validate';
};

export type PostUmbracoSeoToolkitRedirectsValidateErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unprocessable Entity
     */
    422: string;
};

export type PostUmbracoSeoToolkitRedirectsValidateError = PostUmbracoSeoToolkitRedirectsValidateErrors[keyof PostUmbracoSeoToolkitRedirectsValidateErrors];

export type PostUmbracoSeoToolkitRedirectsValidateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRobotsTxtData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type GetUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitRobotsTxtResponse = GetUmbracoSeoToolkitRobotsTxtResponses[keyof GetUmbracoSeoToolkitRobotsTxtResponses];

export type PostUmbracoSeoToolkitRobotsTxtData = {
    body: RobotsTxtSavePostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type PostUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: RobotsTxtSaveResponseModel;
};

export type PostUmbracoSeoToolkitRobotsTxtResponse = PostUmbracoSeoToolkitRobotsTxtResponses[keyof PostUmbracoSeoToolkitRobotsTxtResponses];

export type GetUmbracoSeoToolkitScriptManagerDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/definitions';
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponses = {
    /**
     * OK
     */
    200: Array<ScriptDefinitionViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponse = GetUmbracoSeoToolkitScriptManagerDefinitionsResponses[keyof GetUmbracoSeoToolkitScriptManagerDefinitionsResponses];

export type DeleteUmbracoSeoToolkitScriptManagerScriptData = {
    body: DeleteScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponse = DeleteUmbracoSeoToolkitScriptManagerScriptResponses[keyof DeleteUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponse = GetUmbracoSeoToolkitScriptManagerScriptResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptResponses];

export type PostUmbracoSeoToolkitScriptManagerScriptData = {
    body: CreateScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponse = PostUmbracoSeoToolkitScriptManagerScriptResponses[keyof PostUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptsData = {
    body?: never;
    path?: never;
    query?: {
        domainId?: string;
    };
    url: '/umbraco/seoToolkitScriptManager/scripts';
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponse = GetUmbracoSeoToolkitScriptManagerScriptsResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptsResponses];

export type PostUmbracoSeoToolkitScriptManagerSortScriptsData = {
    body: SortScriptsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/sortScripts';
};

export type PostUmbracoSeoToolkitScriptManagerSortScriptsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/pageChecks';
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksResponses = {
    /**
     * OK
     */
    200: Array<SiteAuditCheckViewModel>;
};

export type GetUmbracoSeoToolkitSiteAuditPageChecksResponse = GetUmbracoSeoToolkitSiteAuditPageChecksResponses[keyof GetUmbracoSeoToolkitSiteAuditPageChecksResponses];

export type PostUmbracoSeoToolkitSiteAuditRunData = {
    body: RunPageCheckPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/run';
};

export type PostUmbracoSeoToolkitSiteAuditRunResponses = {
    /**
     * OK
     */
    200: SiteAuditDetailViewModel;
};

export type PostUmbracoSeoToolkitSiteAuditRunResponse = PostUmbracoSeoToolkitSiteAuditRunResponses[keyof PostUmbracoSeoToolkitSiteAuditRunResponses];

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body: DeleteAuditsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: never;
    path?: never;
    query?: {
        id?: number | string;
    };
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: SiteAuditDetailViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type PostUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body: CreateAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: number | string;
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponse = PostUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof PostUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAuditConfiguration';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses = {
    /**
     * OK
     */
    200: SiteAuditCreateConfigViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudits';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses = {
    /**
     * OK
     */
    200: Array<SiteAuditOverviewViewModel>;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses];

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditData = {
    body: StopAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/stopSiteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeGuid?: string;
    };
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: SitemapPageTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponse = GetUmbracoSeoToolkitSitemapSitemapSettingsResponses[keyof GetUmbracoSeoToolkitSitemapSitemapSettingsResponses];

export type PostUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body: SitemapPageTypeSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type PostUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeKey?: string;
    };
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: SitemapContentSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapContentContentSettingsResponse = GetUmbracoSeoToolkitSitemapContentContentSettingsResponses[keyof GetUmbracoSeoToolkitSitemapContentContentSettingsResponses];

export type PostUmbracoSeoToolkitSitemapContentContentSettingsData = {
    body: SitemapContentSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemapContent/contentSettings';
};

export type PostUmbracoSeoToolkitSitemapContentContentSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiSeoData = {
    body?: never;
    path?: never;
    query?: {
        contentGuid?: string;
        culture?: string;
    };
    url: '/api/seo';
};

export type GetApiSeoResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiSeoResponse = GetApiSeoResponses[keyof GetApiSeoResponses];
