// This file is auto-generated by @hey-api/openapi-ts

export const CreateAuditPostModelSchema = {
    required: ['delayBetweenRequests', 'maxPagesToCrawl', 'name', 'selectedNodeId', 'startAudit'],
    type: 'object',
    properties: {
        name: {
            minLength: 1,
            type: 'string'
        },
        selectedNodeId: {
            type: 'string',
            format: 'uuid'
        },
        checks: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            },
            nullable: true
        },
        startAudit: {
            type: 'boolean'
        },
        maxPagesToCrawl: {
            type: 'integer',
            format: 'int32'
        },
        delayBetweenRequests: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const CreateScriptPostModelSchema = {
    required: ['definitionAlias', 'id', 'name'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            minLength: 1,
            type: 'string'
        },
        definitionAlias: {
            minLength: 1,
            type: 'string'
        },
        fields: {
            type: 'object',
            additionalProperties: {
                type: 'string',
                nullable: true
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DeleteAuditsPostModelSchema = {
    type: 'object',
    properties: {
        ids: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DeleteRedirectsPostModelSchema = {
    type: 'object',
    properties: {
        ids: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DeleteScriptPostModelSchema = {
    type: 'object',
    properties: {
        ids: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DocumentTypeSettingsContentViewModelSchema = {
    type: 'object',
    properties: {
        fields: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SeoFieldViewModel'
                    }
                ]
            },
            nullable: true
        },
        inheritance: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/DocumentTypeSettingsInheritanceViewModel'
                }
            ],
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DocumentTypeSettingsInheritanceViewModelSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DocumentTypeSettingsPostViewModelSchema = {
    required: ['enableSeoSettings', 'nodeId'],
    type: 'object',
    properties: {
        nodeId: {
            type: 'string',
            format: 'uuid'
        },
        enableSeoSettings: {
            type: 'boolean'
        },
        fields: {
            type: 'object',
            additionalProperties: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/DocumentTypeValuePostViewModel'
                    }
                ],
                nullable: true
            },
            nullable: true
        },
        inheritanceId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DocumentTypeSettingsViewModelSchema = {
    type: 'object',
    properties: {
        contentModel: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/DocumentTypeSettingsContentViewModel'
                }
            ],
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DocumentTypeValuePostViewModelSchema = {
    required: ['useInheritedValue'],
    type: 'object',
    properties: {
        useInheritedValue: {
            type: 'boolean'
        },
        value: {
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const DomainViewModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const FieldItemViewModelSchema = {
    required: ['onlyShowIfInherited'],
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true
        },
        value: {
            type: 'string',
            nullable: true
        },
        onlyShowIfInherited: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const FieldPreviewerViewModelSchema = {
    type: 'object',
    properties: {
        group: {
            type: 'string',
            nullable: true
        },
        view: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ImportRedirectsFileExtensionSchema = {
    enum: ['Csv', 'Excel'],
    type: 'string'
} as const;

export const MetaFieldsSettingsPostViewModelSchema = {
    required: ['nodeId'],
    type: 'object',
    properties: {
        nodeId: {
            type: 'string',
            format: 'uuid'
        },
        culture: {
            type: 'string',
            nullable: true
        },
        userValues: {
            type: 'object',
            additionalProperties: {
                nullable: true
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const MetaFieldsSettingsViewModelSchema = {
    type: 'object',
    properties: {
        fields: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SeoSettingsFieldViewModel'
                    }
                ]
            },
            nullable: true
        },
        groups: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SeoFieldGroupViewModel'
                    }
                ]
            },
            nullable: true
        },
        previewers: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/FieldPreviewerViewModel'
                    }
                ]
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const NamedEntityTreeItemResponseModelSchema = {
    required: ['hasChildren', 'id', 'name'],
    type: 'object',
    properties: {
        hasChildren: {
            type: 'boolean'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        parent: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ReferenceByIdModel'
                }
            ],
            nullable: true
        },
        name: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const PagedNamedEntityTreeItemResponseModelSchema = {
    required: ['items', 'total'],
    type: 'object',
    properties: {
        total: {
            type: 'integer',
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/NamedEntityTreeItemResponseModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const PagedRedirectListModelSchema = {
    required: ['items', 'total'],
    type: 'object',
    properties: {
        total: {
            type: 'integer',
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/RedirectListViewModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const RedirectListViewModelSchema = {
    required: ['id', 'isEnabled', 'statusCode'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        isEnabled: {
            type: 'boolean'
        },
        domain: {
            type: 'string',
            nullable: true
        },
        oldUrl: {
            type: 'string',
            nullable: true
        },
        newUrl: {
            type: 'string',
            nullable: true
        },
        statusCode: {
            type: 'integer',
            format: 'int32'
        },
        lastUpdated: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RedirectViewModelSchema = {
    required: ['id', 'isEnabled', 'isRegex', 'redirectCode'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        domain: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        customDomain: {
            type: 'string',
            nullable: true
        },
        isEnabled: {
            type: 'boolean'
        },
        isRegex: {
            type: 'boolean'
        },
        oldUrl: {
            type: 'string',
            nullable: true
        },
        newUrl: {
            type: 'string',
            nullable: true
        },
        newNodeId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        newCultureIso: {
            type: 'string',
            nullable: true
        },
        redirectCode: {
            type: 'integer',
            format: 'int32'
        },
        lastUpdated: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ReferenceByIdModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtSavePostModelSchema = {
    required: ['skipValidation'],
    type: 'object',
    properties: {
        skipValidation: {
            type: 'boolean'
        },
        content: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtSaveResponseModelSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            nullable: true
        },
        errors: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/RobotsTxtValidationViewModel'
                    }
                ]
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtValidationViewModelSchema = {
    required: ['lineNumber'],
    type: 'object',
    properties: {
        lineNumber: {
            type: 'integer',
            format: 'int32',
            readOnly: true
        },
        error: {
            type: 'string',
            nullable: true,
            readOnly: true
        }
    },
    additionalProperties: false
} as const;

export const SaveRedirectPostModelSchema = {
    required: ['id', 'isEnabled', 'isRegex', 'redirectCode'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        domain: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        customDomain: {
            type: 'string',
            nullable: true
        },
        isEnabled: {
            type: 'boolean'
        },
        isRegex: {
            type: 'boolean'
        },
        oldUrl: {
            type: 'string',
            nullable: true
        },
        newUrl: {
            type: 'string',
            nullable: true
        },
        newNodeId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        newCultureId: {
            type: 'string',
            nullable: true
        },
        redirectCode: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const ScriptDefinitionViewModelSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            nullable: true,
            readOnly: true
        },
        alias: {
            type: 'string',
            nullable: true,
            readOnly: true
        },
        fields: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/ScriptField'
                    }
                ]
            },
            nullable: true,
            readOnly: true
        }
    },
    additionalProperties: false
} as const;

export const ScriptDetailViewModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        definitionAlias: {
            type: 'string',
            nullable: true
        },
        config: {
            type: 'object',
            additionalProperties: {
                type: 'string',
                nullable: true
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ScriptFieldSchema = {
    type: 'object',
    properties: {
        key: {
            type: 'string',
            nullable: true
        },
        name: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        propertyAlias: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const ScriptListViewModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        definitionName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SeoDisplayViewModelSchema = {
    required: ['alias', 'name', 'view'],
    type: 'object',
    properties: {
        alias: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        view: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const SeoFieldEditorViewModelSchema = {
    type: 'object',
    properties: {
        view: {
            type: 'string',
            nullable: true
        },
        config: {
            type: 'object',
            additionalProperties: {
                nullable: true
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SeoFieldGroupViewModelSchema = {
    type: 'object',
    properties: {
        alias: {
            type: 'string',
            nullable: true
        },
        name: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SeoFieldViewModelSchema = {
    required: ['useInheritedValue'],
    type: 'object',
    properties: {
        alias: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        useInheritedValue: {
            type: 'boolean'
        },
        value: {
            nullable: true
        },
        editor: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/SeoFieldEditorViewModel'
                }
            ],
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SeoSettingsFieldViewModelSchema = {
    type: 'object',
    properties: {
        alias: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        groupAlias: {
            type: 'string',
            nullable: true
        },
        value: {
            type: 'string',
            nullable: true
        },
        userValue: {
            nullable: true
        },
        editView: {
            type: 'string',
            nullable: true
        },
        editConfig: {
            type: 'object',
            additionalProperties: {
                nullable: true
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SeoSettingsPostModelSchema = {
    required: ['contentTypeId', 'enabled'],
    type: 'object',
    properties: {
        contentTypeId: {
            type: 'string',
            format: 'uuid'
        },
        enabled: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const SeoSettingsViewModelSchema = {
    required: ['displays', 'isEnabled', 'supressContentAppSavingNotification'],
    type: 'object',
    properties: {
        isEnabled: {
            type: 'boolean'
        },
        supressContentAppSavingNotification: {
            type: 'boolean'
        },
        displays: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SeoDisplayViewModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleSchema = {
    required: ['alias', 'icon', 'link', 'status', 'title'],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        alias: {
            type: 'string'
        },
        icon: {
            type: 'string'
        },
        link: {
            type: 'string'
        },
        status: {
            '$ref': '#/components/schemas/SeoToolkitModuleStatus'
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleStatusSchema = {
    enum: ['NotInstalled', 'Installed', 'Disabled'],
    type: 'string'
} as const;

export const SiteAuditCheckViewModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        description: {
            type: 'string',
            nullable: true
        },
        errorMessage: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SiteAuditCreateConfigViewModelSchema = {
    required: ['allowMinimumDelayBetweenRequestSetting', 'minimumDelayBetweenRequest'],
    type: 'object',
    properties: {
        checks: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SiteAuditCheckViewModel'
                    }
                ]
            },
            nullable: true
        },
        minimumDelayBetweenRequest: {
            type: 'integer',
            format: 'int32'
        },
        allowMinimumDelayBetweenRequestSetting: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const SiteAuditDetailViewModelSchema = {
    required: ['id', 'progress', 'totalPagesFound'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        maxPagesToCrawl: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        totalPagesFound: {
            type: 'integer',
            format: 'int32'
        },
        progress: {
            type: 'number',
            format: 'float'
        },
        status: {
            type: 'string',
            nullable: true
        },
        checks: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SiteAuditCheckViewModel'
                    }
                ]
            },
            nullable: true
        },
        pagesCrawled: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SiteAuditPageDetailViewModel'
                    }
                ]
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SiteAuditOverviewViewModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        createdDate: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SiteAuditPageDetailViewModelSchema = {
    required: ['statusCode'],
    type: 'object',
    properties: {
        url: {
            type: 'string',
            nullable: true
        },
        statusCode: {
            type: 'integer',
            format: 'int32'
        },
        results: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SiteAuditResultDetailViewModel'
                    }
                ]
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SiteAuditResultDetailViewModelSchema = {
    required: ['checkId', 'isError', 'isWarning'],
    type: 'object',
    properties: {
        message: {
            type: 'string',
            nullable: true
        },
        checkId: {
            type: 'integer',
            format: 'int32'
        },
        isError: {
            type: 'boolean'
        },
        isWarning: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const SitemapPageTypeSettingsPostModelSchema = {
    required: ['contentTypeGuid', 'hideFromSitemap'],
    type: 'object',
    properties: {
        contentTypeGuid: {
            type: 'string',
            format: 'uuid'
        },
        hideFromSitemap: {
            type: 'boolean'
        },
        changeFrequency: {
            type: 'string',
            nullable: true
        },
        priority: {
            type: 'number',
            format: 'double',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SitemapPageTypeSettingsViewModelSchema = {
    required: ['hideFromSitemap'],
    type: 'object',
    properties: {
        hideFromSitemap: {
            type: 'boolean'
        },
        changeFrequency: {
            type: 'string',
            nullable: true
        },
        priority: {
            type: 'number',
            format: 'double',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const StopAuditPostModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;