// This file is auto-generated by @hey-api/openapi-ts

export type CreateAuditPostModel = {
    name: string;
    selectedNodeId: string;
    checks?: Array<(number)> | null;
    startAudit: boolean;
    maxPagesToCrawl: number;
    delayBetweenRequests: number;
};

export type CreateScriptPostModel = {
    id: number;
    name: string;
    definitionAlias: string;
    fields?: {
        [key: string]: ((string) | null);
    } | null;
};

export type DeleteAuditsPostModel = {
    ids?: Array<(number)> | null;
};

export type DeleteRedirectsPostModel = {
    ids?: Array<(number)> | null;
};

export type DeleteScriptPostModel = {
    ids?: Array<(number)> | null;
};

export type DocumentTypeSettingsContentViewModel = {
    fields?: Array<(SeoFieldViewModel)> | null;
    inheritance?: ((DocumentTypeSettingsInheritanceViewModel) | null);
};

export type DocumentTypeSettingsInheritanceViewModel = {
    id?: (string) | null;
};

export type DocumentTypeSettingsPostViewModel = {
    nodeId: string;
    enableSeoSettings: boolean;
    fields?: {
        [key: string]: ((DocumentTypeValuePostViewModel) | null);
    } | null;
    inheritanceId?: (string) | null;
};

export type DocumentTypeSettingsViewModel = {
    contentModel?: ((DocumentTypeSettingsContentViewModel) | null);
};

export type DocumentTypeValuePostViewModel = {
    useInheritedValue: boolean;
    value?: unknown;
};

export type DomainViewModel = {
    id: number;
    name?: (string) | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type FieldItemViewModel = {
    name?: (string) | null;
    value?: (string) | null;
    onlyShowIfInherited: boolean;
};

export type FieldPreviewerViewModel = {
    group?: (string) | null;
    view?: (string) | null;
};

export type ImportRedirectsFileExtension = 'Csv' | 'Excel';

export const ImportRedirectsFileExtension = {
    CSV: 'Csv',
    EXCEL: 'Excel'
} as const;

export type MetaFieldsSettingsPostViewModel = {
    nodeId: string;
    culture?: (string) | null;
    userValues?: {
        [key: string]: unknown;
    } | null;
};

export type MetaFieldsSettingsViewModel = {
    fields?: Array<(SeoSettingsFieldViewModel)> | null;
    groups?: Array<(SeoFieldGroupViewModel)> | null;
    previewers?: Array<(FieldPreviewerViewModel)> | null;
};

export type NamedEntityTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ((ReferenceByIdModel) | null);
    name: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<(NamedEntityTreeItemResponseModel)>;
};

export type PagedRedirectListModel = {
    total: number;
    items: Array<(RedirectListViewModel)>;
};

export type RedirectListViewModel = {
    id: number;
    isEnabled: boolean;
    domain?: (string) | null;
    oldUrl?: (string) | null;
    newUrl?: (string) | null;
    statusCode: number;
    lastUpdated?: (string) | null;
};

export type RedirectViewModel = {
    id: number;
    domain?: (number) | null;
    customDomain?: (string) | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: (string) | null;
    newUrl?: (string) | null;
    newNodeId?: (string) | null;
    newCultureIso?: (string) | null;
    redirectCode: number;
    lastUpdated?: (string) | null;
};

export type ReferenceByIdModel = {
    id: string;
};

export type RobotsTxtSavePostModel = {
    skipValidation: boolean;
    content?: (string) | null;
};

export type RobotsTxtSaveResponseModel = {
    content?: (string) | null;
    errors?: Array<(RobotsTxtValidationViewModel)> | null;
};

export type RobotsTxtValidationViewModel = {
    readonly lineNumber: number;
    readonly error?: (string) | null;
};

export type SaveRedirectPostModel = {
    id: number;
    domain?: (number) | null;
    customDomain?: (string) | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: (string) | null;
    newUrl?: (string) | null;
    newNodeId?: (string) | null;
    newCultureId?: (string) | null;
    redirectCode: number;
};

export type ScriptDefinitionViewModel = {
    readonly name?: (string) | null;
    readonly alias?: (string) | null;
    readonly fields?: Array<(ScriptField)> | null;
};

export type ScriptDetailViewModel = {
    id: number;
    name?: (string) | null;
    definitionAlias?: (string) | null;
    config?: {
        [key: string]: ((string) | null);
    } | null;
};

export type ScriptField = {
    key?: (string) | null;
    name?: (string) | null;
    description?: (string) | null;
    propertyAlias?: (string) | null;
};

export type ScriptListViewModel = {
    id: number;
    name?: (string) | null;
    definitionName?: (string) | null;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoFieldEditorViewModel = {
    view?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type SeoFieldGroupViewModel = {
    alias?: (string) | null;
    name?: (string) | null;
    description?: (string) | null;
};

export type SeoFieldViewModel = {
    alias?: (string) | null;
    title?: (string) | null;
    description?: (string) | null;
    useInheritedValue: boolean;
    value?: unknown;
    editor?: ((SeoFieldEditorViewModel) | null);
};

export type SeoSettingsFieldViewModel = {
    alias?: (string) | null;
    title?: (string) | null;
    description?: (string) | null;
    groupAlias?: (string) | null;
    value?: (string) | null;
    userValue?: unknown;
    editView?: (string) | null;
    editConfig?: {
        [key: string]: unknown;
    } | null;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<(SeoDisplayViewModel)>;
};

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export type SeoToolkitModuleStatus = 'NotInstalled' | 'Installed' | 'Disabled';

export const SeoToolkitModuleStatus = {
    NOT_INSTALLED: 'NotInstalled',
    INSTALLED: 'Installed',
    DISABLED: 'Disabled'
} as const;

export type SiteAuditCheckViewModel = {
    id: number;
    name?: (string) | null;
    description?: (string) | null;
    errorMessage?: (string) | null;
};

export type SiteAuditCreateConfigViewModel = {
    checks?: Array<(SiteAuditCheckViewModel)> | null;
    minimumDelayBetweenRequest: number;
    allowMinimumDelayBetweenRequestSetting: boolean;
};

export type SiteAuditDetailViewModel = {
    id: number;
    name?: (string) | null;
    maxPagesToCrawl?: (number) | null;
    totalPagesFound: number;
    progress: number;
    status?: (string) | null;
    checks?: Array<(SiteAuditCheckViewModel)> | null;
    pagesCrawled?: Array<(SiteAuditPageDetailViewModel)> | null;
};

export type SiteAuditOverviewViewModel = {
    id: number;
    name?: (string) | null;
    createdDate?: (string) | null;
    status?: (string) | null;
};

export type SiteAuditPageDetailViewModel = {
    url?: (string) | null;
    statusCode: number;
    results?: Array<(SiteAuditResultDetailViewModel)> | null;
};

export type SiteAuditResultDetailViewModel = {
    message?: (string) | null;
    checkId: number;
    isError: boolean;
    isWarning: boolean;
};

export type SitemapPageTypeSettingsPostModel = {
    contentTypeGuid: string;
    hideFromSitemap: boolean;
    changeFrequency?: (string) | null;
    priority?: (number) | null;
};

export type SitemapPageTypeSettingsViewModel = {
    hideFromSitemap: boolean;
    changeFrequency?: (string) | null;
    priority?: (number) | null;
};

export type StopAuditPostModel = {
    id: number;
};

export type GetUmbracoSeoToolkitModulesResponse = (Array<(SeoToolkitModule)>);

export type GetUmbracoSeoToolkitRobotsTxtResponse = (string);

export type PostUmbracoSeoToolkitRobotsTxtData = {
    requestBody?: (RobotsTxtSavePostModel);
};

export type PostUmbracoSeoToolkitRobotsTxtResponse = ((RobotsTxtSaveResponseModel));

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    descendantId?: string;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = (Array<(NamedEntityTreeItemResponseModel)>);

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    parentId?: string;
    skip?: number;
    take?: number;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = ((PagedNamedEntityTreeItemResponseModel));

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    skip?: number;
    take?: number;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = ((PagedNamedEntityTreeItemResponseModel));

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    contentTypeId?: string;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = ((SeoSettingsViewModel));

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    requestBody?: (SeoSettingsPostModel);
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponse = (string);

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    culture?: string;
    nodeGuid?: string;
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = ((MetaFieldsSettingsViewModel));

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    requestBody?: (MetaFieldsSettingsPostViewModel);
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = ((MetaFieldsSettingsPostViewModel));

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponse = (Array<(FieldItemViewModel)>);

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    nodeId?: string;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = ((DocumentTypeSettingsViewModel));

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    requestBody?: (DocumentTypeSettingsPostViewModel);
};

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = (string);

export type GetUmbracoSeoToolkitNotFoundNotFoundResponse = (string);

export type PostUmbracoSeoToolkitNotFoundNotFoundData = {
    data?: string;
};

export type PostUmbracoSeoToolkitNotFoundNotFoundResponse = (string);

export type GetUmbracoSeoToolkitRedirectsDomainsResponse = (Array<(DomainViewModel)>);

export type PostUmbracoSeoToolkitRedirectsImportResponse = (string);

export type DeleteUmbracoSeoToolkitRedirectsRedirectData = {
    requestBody?: (DeleteRedirectsPostModel);
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectResponse = (string);

export type GetUmbracoSeoToolkitRedirectsRedirectData = {
    id?: number;
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponse = ((RedirectViewModel));

export type PostUmbracoSeoToolkitRedirectsRedirectData = {
    requestBody?: (SaveRedirectPostModel);
};

export type PostUmbracoSeoToolkitRedirectsRedirectResponse = (string);

export type GetUmbracoSeoToolkitRedirectsRedirectsData = {
    orderBy?: string;
    orderDirection?: string;
    pageNumber?: number;
    pageSize?: number;
    search?: string;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponse = ((PagedRedirectListModel));

export type PostUmbracoSeoToolkitRedirectsValidateData = {
    domain?: number;
    fileExtension?: ImportRedirectsFileExtension;
    tempFileId?: string;
};

export type PostUmbracoSeoToolkitRedirectsValidateResponse = (string);

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponse = (Array<(ScriptDefinitionViewModel)>);

export type DeleteUmbracoSeoToolkitScriptManagerScriptData = {
    requestBody?: (DeleteScriptPostModel);
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponse = (Array<(ScriptListViewModel)>);

export type GetUmbracoSeoToolkitScriptManagerScriptData = {
    id?: number;
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponse = ((ScriptDetailViewModel));

export type PostUmbracoSeoToolkitScriptManagerScriptData = {
    requestBody?: (CreateScriptPostModel);
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponse = ((ScriptDetailViewModel));

export type GetUmbracoSeoToolkitScriptManagerScriptsResponse = (Array<(ScriptListViewModel)>);

export type PostUmbracoSeoToolkitSiteAuditSiteAuditData = {
    requestBody?: (CreateAuditPostModel);
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponse = (number);

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditData = {
    requestBody?: (DeleteAuditsPostModel);
};

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditResponse = (string);

export type GetUmbracoSeoToolkitSiteAuditSiteAuditData = {
    id?: number;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponse = ((SiteAuditDetailViewModel));

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponse = ((SiteAuditCreateConfigViewModel));

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponse = (Array<(SiteAuditOverviewViewModel)>);

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditData = {
    requestBody?: (StopAuditPostModel);
};

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditResponse = (string);

export type GetUmbracoSeoToolkitSitemapSitemapSettingsData = {
    contentTypeGuid?: string;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponse = ((SitemapPageTypeSettingsViewModel));

export type PostUmbracoSeoToolkitSitemapSitemapSettingsData = {
    requestBody?: (SitemapPageTypeSettingsPostModel);
};

export type PostUmbracoSeoToolkitSitemapSitemapSettingsResponse = (string);