// This file is auto-generated by @hey-api/openapi-ts

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const NamedEntityTreeItemResponseModelSchema = {
    required: ['hasChildren', 'id', 'name'],
    type: 'object',
    properties: {
        hasChildren: {
            type: 'boolean'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        parent: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/ReferenceByIdModel'
                }
            ],
            nullable: true
        },
        name: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const PagedNamedEntityTreeItemResponseModelSchema = {
    required: ['items', 'total'],
    type: 'object',
    properties: {
        total: {
            type: 'integer',
            format: 'int64'
        },
        items: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/NamedEntityTreeItemResponseModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const ReferenceByIdModelSchema = {
    required: ['id'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtSavePostModelSchema = {
    required: ['skipValidation'],
    type: 'object',
    properties: {
        skipValidation: {
            type: 'boolean'
        },
        content: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtSaveResponseModelSchema = {
    type: 'object',
    properties: {
        content: {
            type: 'string',
            nullable: true
        },
        errors: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/RobotsTxtValidationViewModel'
                    }
                ]
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const RobotsTxtValidationViewModelSchema = {
    required: ['lineNumber'],
    type: 'object',
    properties: {
        lineNumber: {
            type: 'integer',
            format: 'int32',
            readOnly: true
        },
        error: {
            type: 'string',
            nullable: true,
            readOnly: true
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleSchema = {
    required: ['alias', 'icon', 'link', 'status', 'title'],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        alias: {
            type: 'string'
        },
        icon: {
            type: 'string'
        },
        link: {
            type: 'string'
        },
        status: {
            '$ref': '#/components/schemas/SeoToolkitModuleStatus'
        }
    },
    additionalProperties: false
} as const;

export const SeoToolkitModuleStatusSchema = {
    enum: ['NotInstalled', 'Installed', 'Disabled'],
    type: 'string'
} as const;