// This file is auto-generated by @hey-api/openapi-ts

export type CreateAuditPostModel = {
    name: string;
    selectedNodeId: string;
    checks?: Array<number> | null;
    startAudit: boolean;
    maxPagesToCrawl: number;
    delayBetweenRequests: number;
};

export type CreateScriptPostModel = {
    id: number;
    name: string;
    definitionAlias: string;
    fields?: {
        [key: string]: string | null;
    } | null;
};

export type DeleteAuditsPostModel = {
    ids?: Array<number> | null;
};

export type DeleteRedirectsPostModel = {
    ids?: Array<number> | null;
};

export type DeleteScriptPostModel = {
    ids?: Array<number> | null;
};

export type DocumentTypeSettingsContentViewModel = {
    fields?: Array<SeoFieldViewModel> | null;
    inheritance?: DocumentTypeSettingsInheritanceViewModel | null;
};

export type DocumentTypeSettingsInheritanceViewModel = {
    id?: string | null;
};

export type DocumentTypeSettingsPostViewModel = {
    nodeId: string;
    enableSeoSettings: boolean;
    fields?: {
        [key: string]: DocumentTypeValuePostViewModel | null;
    } | null;
    inheritanceId?: string | null;
};

export type DocumentTypeSettingsViewModel = {
    contentModel?: DocumentTypeSettingsContentViewModel | null;
};

export type DocumentTypeValuePostViewModel = {
    useInheritedValue: boolean;
    value?: unknown;
};

export type DomainViewModel = {
    id: number;
    name?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type FieldItemViewModel = {
    name?: string | null;
    value?: string | null;
    onlyShowIfInherited: boolean;
};

export type FieldPreviewerViewModel = {
    group?: string | null;
    view?: string | null;
};

export enum ImportRedirectsFileExtension {
    CSV = 'Csv',
    EXCEL = 'Excel'
}

export type MetaFieldsSettingsPostViewModel = {
    nodeId: string;
    culture?: string | null;
    userValues?: {
        [key: string]: unknown;
    } | null;
};

export type MetaFieldsSettingsViewModel = {
    fields?: Array<SeoSettingsFieldViewModel> | null;
    groups?: Array<SeoFieldGroupViewModel> | null;
    previewers?: Array<FieldPreviewerViewModel> | null;
};

export type NamedEntityTreeItemResponseModel = {
    hasChildren: boolean;
    id: string;
    parent?: ReferenceByIdModel | null;
    name: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedNamedEntityTreeItemResponseModel = {
    total: number;
    items: Array<NamedEntityTreeItemResponseModel>;
};

export type PagedRedirectListModel = {
    total: number;
    items: Array<RedirectListViewModel>;
};

export type RedirectListViewModel = {
    id: number;
    isEnabled: boolean;
    domain?: string | null;
    oldUrl?: string | null;
    newUrl?: string | null;
    statusCode: number;
    lastUpdated?: string | null;
};

export type RedirectViewModel = {
    id: number;
    domain?: number | null;
    customDomain?: string | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: string | null;
    newUrl?: string | null;
    newNodeId?: string | null;
    newCultureIso?: string | null;
    redirectCode: number;
    lastUpdated?: string | null;
};

export type ReferenceByIdModel = {
    id: string;
};

export type RobotsTxtSavePostModel = {
    skipValidation: boolean;
    content?: string | null;
};

export type RobotsTxtSaveResponseModel = {
    content?: string | null;
    errors?: Array<RobotsTxtValidationViewModel> | null;
};

export type RobotsTxtValidationViewModel = {
    readonly lineNumber: number;
    readonly error?: string | null;
};

export type SaveRedirectPostModel = {
    id: number;
    domain?: number | null;
    customDomain?: string | null;
    isEnabled: boolean;
    isRegex: boolean;
    oldUrl?: string | null;
    newUrl?: string | null;
    newNodeId?: string | null;
    newCultureId?: string | null;
    redirectCode: number;
};

export type ScriptDefinitionViewModel = {
    readonly name?: string | null;
    readonly alias?: string | null;
    readonly fields?: Array<ScriptField> | null;
};

export type ScriptDetailViewModel = {
    id: number;
    name?: string | null;
    definitionAlias?: string | null;
    config?: {
        [key: string]: string | null;
    } | null;
};

export type ScriptField = {
    key?: string | null;
    name?: string | null;
    description?: string | null;
    propertyAlias?: string | null;
};

export type ScriptListViewModel = {
    id: number;
    name?: string | null;
    definitionName?: string | null;
};

export type SeoDisplayViewModel = {
    alias: string;
    name: string;
    view: string;
};

export type SeoFieldEditorViewModel = {
    view?: string | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type SeoFieldGroupViewModel = {
    alias?: string | null;
    name?: string | null;
    description?: string | null;
};

export type SeoFieldViewModel = {
    alias?: string | null;
    title?: string | null;
    description?: string | null;
    useInheritedValue: boolean;
    value?: unknown;
    editor?: SeoFieldEditorViewModel | null;
};

export type SeoSettingsFieldViewModel = {
    alias?: string | null;
    title?: string | null;
    description?: string | null;
    groupAlias?: string | null;
    value?: string | null;
    userValue?: unknown;
    editView?: string | null;
    editConfig?: {
        [key: string]: unknown;
    } | null;
};

export type SeoSettingsPostModel = {
    contentTypeId: string;
    enabled: boolean;
};

export type SeoSettingsViewModel = {
    isEnabled: boolean;
    supressContentAppSavingNotification: boolean;
    displays: Array<SeoDisplayViewModel>;
};

export type SeoToolkitModule = {
    title: string;
    alias: string;
    icon: string;
    link: string;
    status: SeoToolkitModuleStatus;
};

export enum SeoToolkitModuleStatus {
    NOT_INSTALLED = 'NotInstalled',
    INSTALLED = 'Installed',
    DISABLED = 'Disabled'
}

export type SiteAuditCheckViewModel = {
    id: number;
    name?: string | null;
    description?: string | null;
    errorMessage?: string | null;
};

export type SiteAuditCreateConfigViewModel = {
    checks?: Array<SiteAuditCheckViewModel> | null;
    minimumDelayBetweenRequest: number;
    allowMinimumDelayBetweenRequestSetting: boolean;
};

export type SiteAuditDetailViewModel = {
    id: number;
    name?: string | null;
    maxPagesToCrawl?: number | null;
    totalPagesFound: number;
    progress: number;
    status?: string | null;
    checks?: Array<SiteAuditCheckViewModel> | null;
    pagesCrawled?: Array<SiteAuditPageDetailViewModel> | null;
};

export type SiteAuditOverviewViewModel = {
    id: number;
    name?: string | null;
    createdDate?: string | null;
    status?: string | null;
};

export type SiteAuditPageDetailViewModel = {
    url?: string | null;
    statusCode: number;
    results?: Array<SiteAuditResultDetailViewModel> | null;
};

export type SiteAuditResultDetailViewModel = {
    message?: string | null;
    checkId: number;
    isError: boolean;
    isWarning: boolean;
};

export type SitemapPageTypeSettingsPostModel = {
    contentTypeGuid: string;
    hideFromSitemap: boolean;
    changeFrequency?: string | null;
    priority?: number | null;
};

export type SitemapPageTypeSettingsViewModel = {
    hideFromSitemap: boolean;
    changeFrequency?: string | null;
    priority?: number | null;
};

export type StopAuditPostModel = {
    id: number;
};

export type GetUmbracoSeoToolkitModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/modules';
};

export type GetUmbracoSeoToolkitModulesResponses = {
    /**
     * OK
     */
    200: Array<SeoToolkitModule>;
};

export type GetUmbracoSeoToolkitModulesResponse = GetUmbracoSeoToolkitModulesResponses[keyof GetUmbracoSeoToolkitModulesResponses];

export type GetUmbracoSeoToolkitRobotsTxtData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type GetUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitRobotsTxtResponse = GetUmbracoSeoToolkitRobotsTxtResponses[keyof GetUmbracoSeoToolkitRobotsTxtResponses];

export type PostUmbracoSeoToolkitRobotsTxtData = {
    body?: RobotsTxtSavePostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkit/robotsTxt';
};

export type PostUmbracoSeoToolkitRobotsTxtResponses = {
    /**
     * OK
     */
    200: RobotsTxtSaveResponseModel;
};

export type PostUmbracoSeoToolkitRobotsTxtResponse = PostUmbracoSeoToolkitRobotsTxtResponses[keyof PostUmbracoSeoToolkitRobotsTxtResponses];

export type GetUmbracoSeoToolkitTreeInfoAncestorsData = {
    body?: never;
    path?: never;
    query?: {
        descendantId?: string;
    };
    url: '/umbraco/seoToolkit/tree/info/ancestors';
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponses = {
    /**
     * OK
     */
    200: Array<NamedEntityTreeItemResponseModel>;
};

export type GetUmbracoSeoToolkitTreeInfoAncestorsResponse = GetUmbracoSeoToolkitTreeInfoAncestorsResponses[keyof GetUmbracoSeoToolkitTreeInfoAncestorsResponses];

export type GetUmbracoSeoToolkitTreeInfoChildrenData = {
    body?: never;
    path?: never;
    query?: {
        parentId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/seoToolkit/tree/info/children';
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponses = {
    /**
     * OK
     */
    200: PagedNamedEntityTreeItemResponseModel;
};

export type GetUmbracoSeoToolkitTreeInfoChildrenResponse = GetUmbracoSeoToolkitTreeInfoChildrenResponses[keyof GetUmbracoSeoToolkitTreeInfoChildrenResponses];

export type GetUmbracoSeoToolkitTreeInfoRootData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/seoToolkit/tree/info/root';
};

export type GetUmbracoSeoToolkitTreeInfoRootResponses = {
    /**
     * OK
     */
    200: PagedNamedEntityTreeItemResponseModel;
};

export type GetUmbracoSeoToolkitTreeInfoRootResponse = GetUmbracoSeoToolkitTreeInfoRootResponses[keyof GetUmbracoSeoToolkitTreeInfoRootResponses];

export type GetUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeId?: string;
    };
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: SeoSettingsViewModel;
};

export type GetUmbracoSeoToolkitSettingsSeoSettingsResponse = GetUmbracoSeoToolkitSettingsSeoSettingsResponses[keyof GetUmbracoSeoToolkitSettingsSeoSettingsResponses];

export type PostUmbracoSeoToolkitSettingsSeoSettingsData = {
    body?: SeoSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSettings/seoSettings';
};

export type PostUmbracoSeoToolkitSettingsSeoSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewData = {
    body?: never;
    path?: never;
    query?: {
        mediaId?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/imagePreview';
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitMetaFieldsImagePreviewResponse = GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses[keyof GetUmbracoSeoToolkitMetaFieldsImagePreviewResponses];

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: never;
    path?: never;
    query?: {
        nodeGuid?: string;
        culture?: string;
    };
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsData = {
    body?: MetaFieldsSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFields/metaFields';
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses = {
    /**
     * OK
     */
    200: MetaFieldsSettingsPostViewModel;
};

export type PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponse = PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses[keyof PostUmbracoSeoToolkitMetaFieldsMetaFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsAdditionalFields';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses = {
    /**
     * OK
     */
    200: Array<FieldItemViewModel>;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsAdditionalFieldsResponses];

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: never;
    path?: never;
    query?: {
        nodeId?: string;
    };
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: DocumentTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponse = GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses[keyof GetUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses];

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsData = {
    body?: DocumentTypeSettingsPostViewModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitMetaFieldsSettings/metaFieldsSettings';
};

export type PostUmbracoSeoToolkitMetaFieldsSettingsMetaFieldsSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoSeoToolkitNotFoundNotFoundResponse = GetUmbracoSeoToolkitNotFoundNotFoundResponses[keyof GetUmbracoSeoToolkitNotFoundNotFoundResponses];

export type PostUmbracoSeoToolkitNotFoundNotFoundData = {
    body?: never;
    path?: never;
    query?: {
        data?: string;
    };
    url: '/umbraco/seoToolkitNotFound/notFound';
};

export type PostUmbracoSeoToolkitNotFoundNotFoundResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/domains';
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponses = {
    /**
     * OK
     */
    200: Array<DomainViewModel>;
};

export type GetUmbracoSeoToolkitRedirectsDomainsResponse = GetUmbracoSeoToolkitRedirectsDomainsResponses[keyof GetUmbracoSeoToolkitRedirectsDomainsResponses];

export type PostUmbracoSeoToolkitRedirectsImportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/import';
};

export type PostUmbracoSeoToolkitRedirectsImportErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unprocessable Content
     */
    422: unknown;
};

export type PostUmbracoSeoToolkitRedirectsImportResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectData = {
    body?: DeleteRedirectsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type DeleteUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: RedirectViewModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectResponse = GetUmbracoSeoToolkitRedirectsRedirectResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectResponses];

export type PostUmbracoSeoToolkitRedirectsRedirectData = {
    body?: SaveRedirectPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitRedirects/redirect';
};

export type PostUmbracoSeoToolkitRedirectsRedirectResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
        orderBy?: string;
        orderDirection?: string;
        search?: string;
    };
    url: '/umbraco/seoToolkitRedirects/redirects';
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponses = {
    /**
     * OK
     */
    200: PagedRedirectListModel;
};

export type GetUmbracoSeoToolkitRedirectsRedirectsResponse = GetUmbracoSeoToolkitRedirectsRedirectsResponses[keyof GetUmbracoSeoToolkitRedirectsRedirectsResponses];

export type PostUmbracoSeoToolkitRedirectsValidateData = {
    body?: never;
    path?: never;
    query?: {
        fileExtension?: ImportRedirectsFileExtension;
        domain?: number;
        tempFileId?: string;
    };
    url: '/umbraco/seoToolkitRedirects/validate';
};

export type PostUmbracoSeoToolkitRedirectsValidateErrors = {
    /**
     * Bad Request
     */
    400: string;
    /**
     * Unprocessable Content
     */
    422: string;
};

export type PostUmbracoSeoToolkitRedirectsValidateError = PostUmbracoSeoToolkitRedirectsValidateErrors[keyof PostUmbracoSeoToolkitRedirectsValidateErrors];

export type PostUmbracoSeoToolkitRedirectsValidateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/definitions';
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponses = {
    /**
     * OK
     */
    200: Array<ScriptDefinitionViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerDefinitionsResponse = GetUmbracoSeoToolkitScriptManagerDefinitionsResponses[keyof GetUmbracoSeoToolkitScriptManagerDefinitionsResponses];

export type DeleteUmbracoSeoToolkitScriptManagerScriptData = {
    body?: DeleteScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type DeleteUmbracoSeoToolkitScriptManagerScriptResponse = DeleteUmbracoSeoToolkitScriptManagerScriptResponses[keyof DeleteUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type GetUmbracoSeoToolkitScriptManagerScriptResponse = GetUmbracoSeoToolkitScriptManagerScriptResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptResponses];

export type PostUmbracoSeoToolkitScriptManagerScriptData = {
    body?: CreateScriptPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/script';
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponses = {
    /**
     * OK
     */
    200: ScriptDetailViewModel;
};

export type PostUmbracoSeoToolkitScriptManagerScriptResponse = PostUmbracoSeoToolkitScriptManagerScriptResponses[keyof PostUmbracoSeoToolkitScriptManagerScriptResponses];

export type GetUmbracoSeoToolkitScriptManagerScriptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitScriptManager/scripts';
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponses = {
    /**
     * OK
     */
    200: Array<ScriptListViewModel>;
};

export type GetUmbracoSeoToolkitScriptManagerScriptsResponse = GetUmbracoSeoToolkitScriptManagerScriptsResponses[keyof GetUmbracoSeoToolkitScriptManagerScriptsResponses];

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: DeleteAuditsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type DeleteUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: SiteAuditDetailViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type PostUmbracoSeoToolkitSiteAuditSiteAuditData = {
    body?: CreateAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponses = {
    /**
     * OK
     */
    200: number;
};

export type PostUmbracoSeoToolkitSiteAuditSiteAuditResponse = PostUmbracoSeoToolkitSiteAuditSiteAuditResponses[keyof PostUmbracoSeoToolkitSiteAuditSiteAuditResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAuditConfiguration';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses = {
    /**
     * OK
     */
    200: SiteAuditCreateConfigViewModel;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditConfigurationResponses];

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/siteAudits';
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses = {
    /**
     * OK
     */
    200: Array<SiteAuditOverviewViewModel>;
};

export type GetUmbracoSeoToolkitSiteAuditSiteAuditsResponse = GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses[keyof GetUmbracoSeoToolkitSiteAuditSiteAuditsResponses];

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditData = {
    body?: StopAuditPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSiteAudit/stopSiteAudit';
};

export type PostUmbracoSeoToolkitSiteAuditStopSiteAuditResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: never;
    path?: never;
    query?: {
        contentTypeGuid?: string;
    };
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: SitemapPageTypeSettingsViewModel;
};

export type GetUmbracoSeoToolkitSitemapSitemapSettingsResponse = GetUmbracoSeoToolkitSitemapSitemapSettingsResponses[keyof GetUmbracoSeoToolkitSitemapSitemapSettingsResponses];

export type PostUmbracoSeoToolkitSitemapSitemapSettingsData = {
    body?: SitemapPageTypeSettingsPostModel;
    path?: never;
    query?: never;
    url: '/umbraco/seoToolkitSitemap/sitemapSettings';
};

export type PostUmbracoSeoToolkitSitemapSitemapSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:57441' | (string & {});
};